- cmd/authd/main.go
- internal/brokers/broker.go
- internal/brokers/dbusbroker.go
- internal/brokers/examplebroker/ExampleBroker
- internal/brokers/examplebroker/com.ubuntu.auth.ExampleBroker.conf
- internal/brokers/examplebroker/com.ubuntu.auth.ExampleBroker.xml
- internal/brokers/examplebroker/configurebroker.sh
- internal/brokers/examplebroker/examplebroker.go
- internal/brokers/examplebroker/examplebrokerbus.go
Up until now, we only had the example broker running locally since we didn't have the `dbus` integration with the daemon. This PR implements the `dbus` calls and the ExampleBroker bus that will handle them.
UDENG-1064
> Initial implementation for the ExampleBroker bus and the dbus communication with the daemon

- internal/brokers/broker.go
- internal/brokers/dbusbroker.go
- internal/brokers/examplebroker/examplebroker.go
- internal/brokers/examplebroker/examplebrokerbus.go
- internal/brokers/manager.go
- internal/responses/responses.go
- pam/pam.go
When writing the tests, some problems emerged that demanded some fixing.
The details of each individual fix are contained in the commit messages.
> Fixes for the brokers package

- internal/brokers/broker.go
Now we have a layout that will be used to request a password change from the user after authentication.
UDENG-1150
> Add newpassword layout type 

- pam/authorization.go
- pam/brokerselection.go
- pam/commands.go
- pam/model.go
- pam/pam.go
- pam/return.go
- pam/userselection.go
- pam/utils_c.go
Reenable default broker selection, even with manual testing.
This allows to store remote or local provider selection upon successful authentication.
When manually testing with the binary instead of the PAM stack, consider local selection as always successful.
To reset the default broker selected for a give user, we can restart the authd process as we don’t store the default broker yet in persistent memory.
UDENG-1177
> Default broker selection

- cmd/authd/main.go
The previous behavior did not work as intended, since it wouldn't register the function during the assignment and instead it becomes an endless recursion.
> Fix cleanup logic in the main func

- internal/brokers/broker.go
- internal/brokers/broker_test.go
- internal/brokers/export_test.go
- internal/brokers/testdata/TestGetAuthenticationModes/golden/get_authentication_modes_and_generate_validator_ignoring_whitespaces_in_supported_values
- internal/brokers/testdata/TestGetAuthenticationModes/golden/get_authentication_modes_and_generate_validators
- internal/brokers/testdata/TestGetAuthenticationModes/golden/get_authentication_modes_and_ignores_invalid_ui_layout
- internal/brokers/testdata/TestGetAuthenticationModes/golden/get_multiple_authentication_modes_and_generate_validators
- internal/brokers/testdata/TestGetAuthenticationModes/golden/successfully_get_authentication_modes
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_form_authentication_mode
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_mode_with_missing_optional_value
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_mode_with_optional_value
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_mode_with_required_value
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_newpassword_authentication_mode
- internal/brokers/testdata/TestSelectAuthenticationMode/golden/successfully_select_qrcode_authentication_mode
- internal/testutils/broker.go
We used to have a static verification for the UI layouts returned by the broker, but those are subject to change according to what the system can currently handle. This means that it's up to PAM to provide which layouts are supported, which fields of those layouts are required and what values those fields support.
This replaces the previous static implementation of validateUILayouts with a dynamic one that takes into consideration what was specified by PAM.
UDENG-1166
> Update validateUILayouts logic

- cmd/authd/daemon/daemon.go
- cmd/authd/main.go
- internal/brokers/broker.go
- internal/brokers/examplebroker/dbus.go
- internal/brokers/manager.go
- internal/brokers/withexamples.go
- internal/brokers/withoutexamples.go
- internal/manager/withexamples.go
- internal/manager/withoutexamples.go
We want the ability to run `authd` with the `examplebroker` in order to run manual tests, but without affecting the cmd package. Since this will be shipped in production, we also needed to change the way the `examplebrokers` are created, since using environment variables would introduce a big security liability.
This PR restores the previous behavior of the cmd package and switches the `examplebrokers` creation to rely on build tags instead, which will not impact the production code.
UDENG-1259
> Restore cmd/authd behavior and rework examplebroker creation

- internal/brokers/examplebroker/broker.go
After some API refinements, we added support for password changes and multifactor authentication, but the examplebroker did not have those functionalities to show yet. This PR does some adjustments to the broker and adds those functionalities.
UDENG-1151
> Extend examplebroker with MFA, password resets and max attempts

- pam/authmodeselection.go
- pam/model.go
Right now, the UI layout is hardcoded in the pam module and just requested in time.
Requests those rather at the start of the transaction, asynchronously, so that then, we can query third parties like GDM.
UDENG-1300
> Allow dynamic request of the UI layout

- internal/services/pam/pam_test.go
- internal/services/pam/testdata/TestAvailableBrokers/golden
- internal/services/pam/testdata/TestGetAuthenticationModes/golden/successfully_get_authentication_modes
- internal/services/pam/testdata/TestGetAuthenticationModes/golden/successfully_get_multiple_authentication_modes
- internal/services/pam/testdata/TestIsAuthorized/golden/denies_authentication_when_broker_times_out
- internal/services/pam/testdata/TestIsAuthorized/golden/empty_data_gets_json_formatted
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_authorizing
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_broker_returns_invalid_access
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_broker_returns_invalid_data
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_calling_second_time_without_cancelling
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_sessionid_is_empty
- internal/services/pam/testdata/TestIsAuthorized/golden/error_when_there_is_no_broker
- internal/services/pam/testdata/TestIsAuthorized/golden/successfully_authorize
- internal/services/pam/testdata/TestIsAuthorized/golden/successfully_authorize_if_first_call_is_canceled
- internal/services/pam/testdata/TestSelectAuthenticationMode/golden/successfully_select_mode_with_missing_optional_value
- internal/services/pam/testdata/TestSelectAuthenticationMode/golden/successfully_select_mode_with_required_value
- internal/services/pam/testdata/TestSelectBroker/golden/successfully_select_a_broker_and_creates_the_session
- internal/testutils/broker.go
Package tests for `internal/services/pam`.
UDENG-1172
> PAM service tests

- internal/services/pam/pam_test.go
Still keeps the brokers global, but create per test PAM client and service.
The service will rely on the cache itself, which will be different per tests to assert on addition/update of given users.
> Create a per test PAM client in pam services.

- internal/services/pam/pam_test.go
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_when_there_is_no_broker
Before introducing the cache in PAM service, let’s simplify the tests even more.
> Simplify PAM service tests

- internal/cache/db_test.go
- internal/cache/tests/serialization.go
Move those and link from a subpackage, to ensure we know exactly what we import in a package (not importing tests by accident). This will be reused in the PAM/NSS services tests to load and dump the database.
> Allow easy DB test helpers being exported

- cmd/authd/daemon/daemon.go
- internal/services/manager.go
- internal/services/withexamples.go
- internal/services/withoutexamples.go
As this relies heavily on the services, it’s more logical to have it in the same directory, to coordinate any child services.
> Move service manager at the root of services

- internal/brokers/examplebroker/broker.go
- internal/brokers/responses/responses.go
- internal/brokers/testdata/TestIsAuthenticated/golden/empty_data_gets_json_formatted
- internal/brokers/testdata/TestIsAuthenticated/golden/error_when_calling_isauthenticated_a_second_time_without_cancelling
- internal/brokers/testdata/TestIsAuthenticated/golden/successfully_authenticate
- internal/brokers/testdata/TestIsAuthenticated/golden/successfully_authenticate_after_cancelling_first_call
- internal/services/pam/testdata/TestIsAuthenticated/golden/empty_data_gets_json_formatted
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_when_calling_second_time_without_cancelling
- internal/services/pam/testdata/TestIsAuthenticated/golden/successfully_authenticate
- internal/services/pam/testdata/TestIsAuthenticated/golden/successfully_authenticate_if_first_call_is_canceled
- internal/testutils/broker.go
- pam/authentication.go
Now that the semantic is around authentication, use granted as a keyword instead of allowed.
Remove a couple of hardcoded data.
> Rename allowed to granted as access accepted

- internal/brokers/broker_test.go
- internal/brokers/manager_test.go
- internal/brokers/testdata/TestIsAuthenticated/golden/error_when_authenticating
- internal/brokers/testdata/TestIsAuthenticated/golden/error_when_calling_isauthenticated_a_second_time_without_cancelling
- internal/brokers/testdata/TestNewManager/golden/creates_without_autodiscovery_when_configuredbrokers_is_set
- internal/brokers/testdata/TestNewSession/golden/successfully_start_a_new_session
- internal/brokers/testdata/TestNewSession/golden/successfully_start_a_new_session_with_the_correct_broker
- internal/services/pam/testdata/TestSelectBroker/golden/successfully_select_a_broker_and_creates_the_session
- internal/testutils/broker.go
The `brokers.Manager` has to manage multiple sessions and brokers at once and we were not testing that. This PR adds a couple of test cases to cover those scenarios, mainly:
- Starting a session on the correct broker;
- Ending a session on the correct broker;
- Creating a new manager without autodiscovery if []configuredBrokers was set;
This also updates the broker tests to use a MockBroker per test family rather than creating a MockBroker per test case. This saves memory and speed whilst also providing a more "realistic" environment in which a Broker attends multiple calls. 
UDENG-1329
> Updating broker tests to cover some implicit cases

- .github/dependabot.yml
Dependabot is a handy tool to track our dependencies updates and check for unmaintained ones (especially common in the Rust ecosystem), so we have to add it to our repository.
UDENG-1412
> ci: Set up dependabot on the repository

- .github/dependabot.yml
Doing some improvements on the dependabot config file to prefix the bump commits with our new pull request naming standards.
> ci: Update dependabot config

- internal/cache/db.go
- internal/cache/db_test.go
- internal/cache/export_test.go
- internal/cache/tests/serialization.go
Export database name for cachetests to be reusable. We are now exporting the cache tests internal implementations for testing purposes with linking. This will be reused when working on making the service manager failing.
UDENG-1477
> tests(cache): Export db name

- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/daemon_test.go
- cmd/authd/daemon/export_test.go
- cmd/authd/daemon/fs.go
Ensure we can run without pre-existing cache directory. Check also its permission for safety measures.
Adapt and fix tests to cover those use cases and impossibilities to create manager.
UDENG-1477
> fix(daemon) Allow running without pre-created cache directory

- internal/brokers/broker_test.go
- internal/brokers/dbusbroker.go
- internal/brokers/examplebroker/ExampleBroker
- internal/brokers/examplebroker/com.ubuntu.auth.ExampleBroker.conf
- internal/brokers/examplebroker/com.ubuntu.auth.ExampleBroker.xml
- internal/brokers/examplebroker/dbus.go
- internal/brokers/testdata/broker.d/invalid_brokers/no_dbus_interface
- internal/testutils/broker.go
As correctly pointed out by Marco, the bus interface should be a specific value as it's supposed to define an expected way of communication with the bus object rather than a custom value that is configurable.
UDENG-1409
> refactor(brokers): bus interface no longer overridable through broker config

- internal/services/manager_test.go
- internal/services/testdata/TestRegisterGRPCServices/golden
The `services.Manager` didn't have tests yet, this PR fixes that. 
UDENG-1419
> tests(services): Add tests to services.Manager

- internal/brokers/examplebroker/broker.go
- internal/brokers/examplebroker/dbus.go
Fix missing userinfo metadata when granting access. In the selection of userinfo, we missed the marker in the data json struct in the examplebroker. Readding it.
Fix multiple MFAs handling logic.
Removal of dead code.
Fixing cycling imports.
Labels changes.
> fix(examplebroker): Mutliple fixes to example brokers

- pam/authentication.go
- pam/authmodeselection.go
- pam/newpasswordmodel.go
The broker decides if the user needs to change his/her password. In this first iteration, we only support two fields that should match and basic error printing.
The view is optionally skippable.
DEENG-1180.
> feat(pam) Implement newpasswd view

- pam/authentication.go
- pam/formmodel.go
We need to reset the form fields on invalid password (especially with hidden characters) to ensure that the new password typed by the user is vanilla.
We should not restore the state when resending password for a similar reason.
> fix(pam): Reset form field and do not restore state

- .github/dependabot.yml
Having the scopes defined in the commit message was adding a "(deps)" tag to it, but that's exactly the purpose of the prefixes that we already add.
> ci: Remove scopes from dependabot config

- internal/brokers/examplebroker/broker.go
This PR consists of two important fixes:
1) Fix the logic for updating the userLastSelectedMode: we were updating it every time IsAuthenticated was called, which is not ideal (the user could be "locked" on a failing state). Now, it only updates when access is `Granted`. For MFA cases, we store and use the first selected mode (as it would be the "main" authentication mode).
2) Fix the way we get the password reset modes. Before, they were being returned by the getSupportedModes function and they were being shown on the first list of modes returned by the broker (not ideal, since the user should only be able to reset the password AFTER authenticating). Now, they're parsed separately and an error is returned if the user needs to reset the password, but no mode is available.
UDENG-1494
> fix(examplebroker): Update userLastSelectedMode and getPasswdModes logics to be more concise

- authd.proto
- pam/authentication.go
* Fix proto file syntax
* Remove dead code using userinfo which will never be passed to the PAM module, we only need them on the service side for the NSS cache.
> maint: linting and dead code removal

- pam/model.go
There was an event race if after broker selection, the supported UI layouts took time to get back.
You then go back to user selection without really leaving the BrokerSelection page, which leaded to then reselecting the authentication layout from the previous session.
This fix will help in our next UI without any "stage" paths, when we don’t necessarily go back to broker selection to change users.
> fix(pam): avoid restoring previous session in user selection mode

- internal/brokers/examplebroker/broker.go
`newpassword` modes are conditional and should not be returned as "general" authentication modes when `getSupportedModes` is called by GAM.
> fix(examplebroker): stop returning newpassword as supportedModes when calling GAM

- internal/brokers/examplebroker/broker.go
- internal/brokers/withexamples.go
We were using 5 milliseconds as a wait time for the dbus mock to start, despite already knowing that it wasn't enough (see [this commit](https://github.com/ubuntu/authd/commit/485a7b0343dc287f91062f99c5cb2234c0ea38d7)). This increases the wait time to 500 milliseconds.
Also, some of the returned values of the examplebroker represented mock values that were invalid in a real environment, so they had to be updated as well.
UDENG-1491
> fix(examplebroker): Increase wait time for the mock start + update some return values of the broker

- cmd/authd/daemon/daemon.go
The arg check will raise an early error, doing this for us.
> fix(cmd): print usage on unknown subcommand

- cmd/authd/daemon/config.go
- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/daemon_test.go
- cmd/authd/daemon/export_test.go
- internal/brokers/broker_test.go
- internal/brokers/export_test.go
- internal/brokers/manager.go
- internal/brokers/manager_test.go
- internal/consts/consts.go
- internal/services/manager.go
- internal/services/manager_test.go
- internal/services/pam/pam_test.go
* Allow exporting them as environment variable or via a configuration file (using a subdomain, to ensure it’s not exposed at the root level).
* Don’t export them as flags: this is niche-case enough to be as configuration rather than flags.
* Ensure we minimize the usage of `With*()` by only having it for really optional parameter. For the others, it means that this directory should be explicit passed and the const default is initiliazed at the start of the program, just before loading overidden configuration.
* Align the naming around those variables.
UDENG-1392
> Make cache/brokers/socket directories configurable

- internal/cache/db.go
If dirEntry.info() returns an ErrNotExist error, it means that the file is no longer available, which means that the process doesn't exist anymore, so we can ignore it.
Closes #79
UDENG-1521
> fix(cache): Ignore info() err on getActiveUsers if it is ErrNotExist

- .github/workflows/qa.yaml
Adding a step to check if the daemon still builds with the `withexamplebroker` build tag to the sanity check job.
UDENG-1452
> ci: Add step to build cmd/authd with withexamplebroker tag to QA job

- go.mod
`govulncheck` was updated and now some CI tests are failing due to security vulnerabilities in some standard library packages. This can be fixed by bumping the required go version to 1.21.4, which is done in this PR.
> deps(go): bump go to 1.21.4

- pam/go-loader/libpam-authd.pam-auth-update
- pam/go-loader/module.c
- pam/pam.go
When a Go shared library is loaded from C, go starts various goroutine (as `init()` at first) and if the loading code is then performing a fork we end up having an undefined behavior and very likely, deadlocks.
To avoid this we need to ensure that the module is initialized after the loading application has forked, and this for sure has happened when the application calls the PAM functions that a module exposes.
As per this, here we re-implement the PAM modules functions and for each action we load the module if it has not been loaded already, otherwise we `dload` it and we redirect each call to the loaded library.
This is safe because a PAM application is always perform operations in the same thread so once we've defined the "main" one we can create new ones in the module safely.
By using …
> pam: Add a simple go-loader pam module to wrap the go-generated modules

- internal/testutils/rust.go
We were always instrumenting the Rust binaries, since the CoverDir() was never empty.
> fix(testutils): Fix logic error when gathering Rust coverage

- gotestcov
Sometimes, we want to run only specific tests that don't include the NSS module (which means no Rust coverage). The script quit with an error if it could not merge the Rust coverage to the Go one. This is fine for the CI since we want all coverage, but the script needs a change to prevent this.
> fix: Allow test and cover script to run without enabling Rust coverage

- internal/services/pam/pam_test.go
- internal/users/export_test.go
- internal/users/getpwent_c.go
- internal/users/getpwent_test.go
- internal/users/testdata/TestCleanLocalGroups/golden/cleans_up_multiple_users_from_group
- internal/users/testdata/TestCleanLocalGroups/golden/cleans_up_multiple_users_from_multiple_groups
- internal/users/testdata/TestCleanLocalGroups/golden/cleans_up_user_from_group
- internal/users/testdata/TestCleanLocalGroups/golden/cleans_up_user_from_multiple_groups
- internal/users/testdata/TestCleanLocalGroups/golden/error_on_any_unignored_delete_gpasswd_error
- internal/users/testdata/TestCleanUserFromLocalGroups/golden/cleans_up_user_from_group
- internal/users/testdata/TestCleanUserFromLocalGroups/golden/cleans_up_user_from_multiple_groups
- internal/users/testdata/inactive_user_in_many_groups.group
- internal/users/testdata/inactive_user_in_one_group.group
- internal/users/testdata/inactive_users_in_many_groups.group
- internal/users/testdata/inactive_users_in_one_group.group
- internal/users/tests/tests.go
- internal/users/users.go
- internal/users/users_test.go
Due to limitations with our `cache`, we can't know exactly which users were deleted when the database was corrupted and it got cleared up and rebuilt, so we need to have a routine that periodically cleans the local groups from any unexistent users.
This is a complex task that could potentially spawn a lot of subprocesses (in the form of `gpasswd --delete` calls) to clean the local groups. However, the dominant factor of complexity in the code is the number of groups (and the number of users that belong to those groups) rather than the number of existent users. Since we query directly `/etc/groups` to look for the groups, we are only dealing with local groups here and, as such, we should be fine with performance.
UDENG-1864
> feat(users/services): Local groups cleanup

- README.md
- debian/control
Properly describe the package.
> doc: update package description

- .github/workflows/qa.yaml
- gotestcov
By default, Go only calculates coverage of the package being tested. While this is good to see how effective our unit tests are, we also miss the coverage on more complex tests that test more than one package at a time.
By adding the `-coverpkg=./...` flag, Go now calculates the test coverage on the current package + all of the sub-packages.
> fix(CI/coverage): Cover all packages by default

- go.mod
- go.sum
Bump go-pam requirement so that we do ignore unused-variables warning on cgo generated code.
It basically includes https://github.com/msteinert/pam/pull/22
Closes: #179 
UDENG-2104
> deps(go): Bump dependency on go-pam to ignore compilation warning

- internal/brokers/examplebroker/broker.go
- pam/internal/adapter/authentication.go
- pam/internal/adapter/model.go
This generates an asymmetric private/public key pair at broker creation time. We let it panic as this broker is only for testing purposes.
This encryption key is then passed at session creation. Note that the broker can create a new key for each session if desired.
The chosen encryption is sha512. The public key is passed as X.509 standard, encoded as base64.
Testing is only covered at integration test level, as this requires a broker and exercise the PAM module itself.
UDENG-2014
> feat: Implement encryption when exchanging challenge

- internal/brokers/dbusbroker.go
- internal/brokers/examplebroker/ExampleBroker
- internal/brokers/examplebroker/dbus.go
- internal/brokers/manager_test.go
- internal/brokers/testdata/TestNewManager/golden/ignores_any_unknown_sections_and_fields
- internal/brokers/testdata/broker.d/extra_fields/extra_fields
- internal/brokers/testdata/broker.d/invalid_brokers/no_brand_icon
- internal/brokers/testdata/broker.d/invalid_brokers/no_dbus_name
- internal/brokers/testdata/broker.d/invalid_brokers/no_dbus_object
- internal/brokers/testdata/broker.d/invalid_brokers/no_name
- internal/brokers/testdata/broker.d/mixed_brokers/valid
- internal/brokers/testdata/broker.d/not_on_bus/not_on_bus
- internal/brokers/testdata/broker.d/valid_brokers/valid
- internal/brokers/testdata/broker.d/valid_brokers/valid_2
- internal/testutils/broker/broker.go
Move all key name under authd section. This way, we delimit the section mandatory for authd from others, the rest is available for the broker to reuse.
Adapt existing and add additional tests for it.
UDEENG-2007.
> feat(authd): rework brokers config file

- internal/services/pam/pam_test.go
- internal/users/localgroups/tests/tests.go
- internal/users/manager_test.go
We had some duplicated code in our tests, but after #185 we now have the `gpasswd` mock setup wrapped in new helpers that allow us to deduplicate some code.
> tests: Switch to gpasswd mock helper functions

- debian/changelog
The PPA builds are available at https://launchpad.net/~justdenis/+archive/ubuntu/authd/
UDENG-2163
> maint: Update changelog for 0.2 release

- Cargo.lock
- nss/Cargo.toml
There were some issues with some crate dependencies in the project. The main ones are:
- cc -> Dependabot bumped cc to 1.84, but this release was rollbacked due to issues with other ecosystems:
https://github.com/rust-lang/cc-rs/releases/tag/1.0.84
- h2 -> The previous 0.3.21 version had a CVE-2019-9514, reported in https://rustsec.org/advisories/RUSTSEC-2024-0003. 
Plus other bumps for minor versions that were not updated due to Dependabot only watching for dependencies listed in the manifest files.
> deps: Fix Rust dependencies

- .github/workflows/qa.yaml
codecov v4 action requires now a token.
> maint(ci): Inject token to report coverage with v4

- .github/workflows/qa.yaml
We use a directory strategy to ship it, which is compatible with multiple platforms using a relative directory, and rely on autosearch so that only this subdirectory contains all codecov related content.
> maint(ci): align coverage reporting with Pro for WSL project

- go.mod
- go.sum
- pam/internal/adapter/authentication.go
- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/gdmmodel.go
- pam/internal/adapter/gdmmodel_convhandler_test.go
- pam/internal/adapter/gdmmodel_helpers_test.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/gdmmodel_uimodel_test.go
- pam/internal/adapter/model.go
- pam/internal/adapter/userselection.go
- pam/internal/gdm/conversation.go
- pam/internal/gdm/conversation_test.go
- pam/internal/gdm/extension.h
- pam/internal/gdm/extension_test.go
- pam/internal/gdm/main_test.go
- pam/internal/gdm_test/gdm_utils.go
- pam/internal/pam_test/module-transaction-dummy.go
- pam/internal/pam_test/pam-client-dummy.go
- pam/internal/pam_test/pam-client-dummy_test.go
- pam/internal/pam_test/utils.go
- pam/pam.go
Add a model to implement the communication between GDM and this pam
module using the JSON private protocol.
Added tests that mimic the behavior of what GDM ui should do,
implementing a pam transaction handler that supports the GDM binary
protocol.
This does not include fully integration tests yet, to make review _smaller_...
UDENG-1372
> feat(pam/adapter): Add Gdm model implementation

- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_switching_broker
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/deny_authentication_if_user_does_not_exist
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/exit_authd_if_local_broker_is_selected
- pam/integration-tests/testdata/TestCLIChangeAuthTok/golden/exit_authd_if_local_broker_is_selected
- pam/internal/adapter/model.go
pam/adapter: Do not resize brokwerselection window on window changes
In terminal mode we're monitoring the window size and eventually changing
the broker selection list (only) that forces a fullscreen view of them.
This is something that it's not needed on the kind of "app" we're
building because it brings user context away (e.g. What was I
authenticating for?!) but also it makes testing the interface very hard
because will make bubbletea to potentially hide some error messages (as golden files change shows).
This helps #233
> fix(pam): Do not use fullscreen views in interactive mode

- Cargo.lock
- nss/Cargo.toml
- nss/src/passwd/mod.rs
We used to rely on another crate to do this checking, but it created problems down the line (possibly due to multithreading). Switching to `procfs`, which works by parsing /proc rather than more complex OS features, makes the function simpler and safer to use.
> fix(NSS): Rework check of parent process in should_pre_check

- internal/log/log.go
- internal/log/log_test.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_switching_broker
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/exit_authd_if_local_broker_is_selected
- pam/integration-tests/testdata/TestCLIChangeAuthTok/golden/exit_authd_if_local_broker_is_selected
- pam/internal/adapter/authentication.go
- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/model.go
- pam/internal/adapter/userselection.go
- pam/main-cli.go
- pam/pam.go
Log messages in the pam module were incomplete and at times they were using an higher priority than expected, and when authenticating with sudo or friends in an interactive terminal they were often spamming the session, breaking the bubbletea interface.
At the same time when running the module in such scenario or when it is loaded from other components such as ssh or desktop environments, it wasn't easy to debug it.
Said this:
- Use PAM messages more to output errors when the interactive interface is over
- Add client output to the integration tests logs
- Add more debug messages where it matters
- Implement `log` so that logging handlers can be defined for each level
- Add a journal log handler that uses systemd journal as output
- Use warning level logging in interactive terminals
- pam …
> feat(pam): Cleanup logging, disable info messages in terminal mode and use journal when possible

- internal/testutils/dbus.go
- nss/src/client/mod.rs
- nss/src/group/mod.rs
- nss/src/lib.rs
- nss/src/passwd/mod.rs
- nss/src/shadow/mod.rs
dbus can do some NSS calls and, if this happens during authd startup, the daemon will hang (this mainly affected cases where we wanted to run authd with the examplebroker built-in as, in order to do that, we were running a separate system bus of our own).
To prevent this from happening again and to add layers of protection, our NSS requests will have a timeout and we are also skipping the dbus calls to NSS in our dbus mock.
UDENG-2511
UDENG-2510
> fix: Add timeout to requests and skip dbus NSS lookup on dbus mock

- .github/workflows/qa.yaml
Ubuntu ddebs repos are a bit flaky, so in case of failures just go manual.
It's far from being nice, but without symbols we can't skip do proper leak-checks, so the other option is skipping those in such case but I feel it's worse.
/cc @didrocks
> ci/qa: Try to install debug symbols from launchpad if ddebs fails

- .github/workflows/qa.yaml
- nss/integration-tests/integration_test.go
- pam/integration-tests/cli_test.go
In case of failures we should save the artifacts we have prepared so that can be inspected better (or we can watch the .gif files).
> feat(CI): save test artifacts on failures

- nss/src/lib.rs
- pam/pam.go
This call could hang forever if the file was present but not ready yet, so we should add a timeout instead to prevent deadlocks.
UDENG-2508
> fix: Add timeout when connecting to authd socket in PAM

- debian/pam-configs/authd
This ensures this is inserted at the correct place inside the pam stack. Use default=ignore to let the registration pass if we can't connect to authd.
UDENG-2495
> fix(pam): pam account registration integration

- nss/integration-tests/helper_test.go
- nss/src/client/mod.rs
- nss/src/lib.rs
- nss/src/logs/mod.rs
When using the Debug level, we were getting spammed by a lot of gRPC connection logs from tonic and it looks like we can't control the logging level individually. So, instead, let's tune down our log messages to Info instead of Debug so that we can have a cleaner output of what we want.
> refactor(NSS): Tune logging to Info instead of Debug

- go.mod
- go.sum
- pam/main-cli.go
- pam/pam.go
As per pam_sm_chauthtok(3) PAM may call the function twice, with
different flags, so in such case just ignore the request and wait for
the next one to happen.
> fix(pam): Do not try to change the password twice but only after preliminary checks

- pam/integration-tests/gdm_test.go
- pam/pam.go
Some cleanups on logging of PAM module and on tests:
- Avoid spamming the CI logs with gdm logs unless we're failing
- Disable any (stdout/stederr) output if pam silent flag is used
- Use module debug logging when testing gdm too, but do not present it unless required
> cleanup(pam): handle silent flag on module and improve logging on gdm tests

- internal/services/pam/pam_test.go
- internal/services/pam/testdata/TestGetPreviousBroker/get-previous-broker.db
We will not store the local broker in the database itself, so better to use a real broker there.
As we generate the mock broker id dynamically for the tests, change it on the fly.
> fix(tests): do not use local broker for pam test

- internal/services/pam/pam.go
- internal/services/pam/pam_test.go
- internal/users/cache/db_test.go
- internal/users/cache/getbroker.go
- internal/users/manager.go
- internal/users/manager_test.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/autoselect_local_broker_for_local_user
- pam/integration-tests/testdata/tapes/local_user.tape
This autoselect (even on first login) the local broker, any "local" users.
It means:
- Any users in the file service (passwd) will immediately being autoselected as local.
- Other "locally dealt but remote" users (handled by sss, winbind…) will be offered the broker prompt on its first login on the system. Once logged in once, even without authd installed, then the user will be reachable through NSS, and the "local" broker will then be autoselected.
- Any users in our cache will get through the traditional broker autoselection once the login was successful for this broker
- Any users not in our cache and not resolved through NSS will be offered the broker selection dialog.
For local users which can be resolved with NSS, the NSS request will only be performed once after the service starts …
> feat: Autoselect and return "local" for non authd users

- .github/workflows/qa.yaml
We have some C code in authd that we're checking at runtime, but we should also ensure that static checks pass on it.
So let's add another CI job handling this.
More than for the simpler code we've so far, this is something that is quite welcome by #264.
> feat(ci/qa): Add C code sanity checks with static analyzer

- .github/workflows/qa.yaml
- pam/go-exec/module.c
- pam/integration-tests/modulehelpers_test.go
Only manage the module log domain by default so that loader apps won't
be affected and we ensure that every action can have its logging file.
This fixes a race that we hit in tests in arm since in some scenarios
it could happen that:
- pam_authd_exec.so is loaded by PAM
- libglib is also loaded in memory as its dependency
- pam_authd_exec.so is unloaded but libglib in memory is not unloaded
- loading again pam_authd_exec.so in the same test binary may end up
setting the glib writer function again, which leads to an assertion.
This is not the case anymore since we have a local writer that is
invoked only when our log handler is called
UDENG-2665
> fix(pam/go-exec): Use per-action log handlers to log write logs

- internal/testsdetection/integrationtests.go
- internal/testsdetection/testdata/binary.go
- internal/testsdetection/testsdetection.go
- internal/testsdetection/testsdetection_test.go
- internal/testutils/golden.go
Add `MustBeTesting` assertion to ensure we run in tests. This assertion will panic if we don’t run in traditional tests (gotest)
or integration tests.
Add tests for detection tests
Those tests address:
- traditional tests detection started by go test
- integration tests detection for a binary built with the
integrationtests tag.
- ensure we don’t falsy report integration tests for binary without the
tag.
Hook up coverage report, even for the subprocess, with this.
UDENG-2563
UDENG-2584
> feat: detect traditional and integration tests

- go.mod
- internal/services/authorizer/authorizer.go
- internal/services/authorizer/authorizer_test.go
- internal/services/authorizer/authorizertests/authorizertests.go
- internal/services/authorizer/export_test.go
- internal/services/authorizer/internal_test.go
- internal/services/authorizer/servercreds.go
- internal/services/authorizer/testutils.go
* The Authorizer can decode from a context then current per user id (and pid) which connected to an unix socket. Then, it provides methods for authorization. One of them is only authorizing if the current user is root.
* Add unit and package tests for it.
* Export test helpers for other package and integration tests  
* Make available to other packages some helpers to modify authorizer creation or lifecycle.
* Ensure we have helpers for integration tests too.
* All those helpers can be run without panicking in other local or integration tests.
UDENG-2563
UDENG-2584
> feat: authorizer to handle unix socket peer user

- .github/workflows/qa.yaml
- pam/integration-tests/modulehelpers_test.go
As per commit c87e5928 we fail building on warnings, and we may get one if AUTHD_PAM_MODULES_PATH env variable is unset.
To prevent this, let's just guess it at test time if none is explicitly set so that developers life should be better
> pam/integration-tests: Set the AUTHD_PAM_MODULES_PATH by default

- .github/workflows/qa.yaml
In case of cgo-related failures when building in ASAN mode it allows to catch issues better, since we'll have debug symbols with non-temporary locations
> fix(ci/qa): Run ASAN integration tests using built binary

- nss/integration-tests/helper_test.go
- nss/integration-tests/integration_test.go
This way, we don't need to have an original output storage and remove it from each commands.
Also, all errors are directly the one from our service.
Remove also an unused variable.
> maint: simplify NSS integration tests by targetting our service directly

- internal/daemon/daemon_test.go
These tests sometimes failed (both in CI and in Launchpad) likely due to slower runners not being able to setup the expected behavior in the amount of time that we gave them, so increasing the wait time should prevent this from happening.
> fix: Increase sleep time in some `internal/daemon` tests

- internal/brokers/broker_test.go
- internal/brokers/manager_test.go
- pam/integration-tests/gdm_test.go
- pam/internal/adapter/commands.go
Avoid reusing the same local broker string everywhere, making it easier to change such ID in case we need in future, but also to making harder to errors due to typos.
> refactor: Use brokers.LocalBrokerName definition everywhere

- pam/go-exec/module.c
- pam/integration-tests/exec_test.go
- pam/integration-tests/gdm_test.go
- pam/integration-tests/modulehelpers_test.go
- pam/main-exec.go
- pam/pam.go
- pam/pam_test.go
As per my latest tests on main, I've noticed that once authd was performing `setcred` in SSHd, we were not properly reacting to the second call to it leading to a total hang when connecting to any authd-powered server, so went analyzing the causes and found the solution for it.
This is the main reason:
Instead of relying on signal as GLib does just use waitpid on a separate
thread as this is safer to use because our library might be loaded by
other applications that may set a different handler on SIGCHLD, breaking
us, and making our wait to be never-ending.
This is particularly the case of sshd, because it creates a subprocess
where actions are executed, replacing our SIGCHLD handler causing the
module to hang forever during a second call to setcred.
UDENG-2695
> fix(pam/go-exec): Address SSH hangs by using simpler waitpid to monitor children lifetime 

- examplebroker/broker.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_successfully_with_preset_user
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/autoselect_local_broker_for_local_user
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/autoselect_local_broker_for_local_user_preset
- pam/integration-tests/testdata/tapes/local_user_preset.tape
- pam/integration-tests/testdata/tapes/simple_auth_with_preset_user.tape
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/model.go
- pam/internal/adapter/userselection.go
- pam/main-cli.go
Ensure that terminal output is not touched unless we really need to.
This is something that is also required for #314 so having it earlier would help that PR too.
UDENG-2608
> fix(pam): Start broker and user selection only if required, without touching terminal

- examplebroker/broker.go
- internal/brokers/broker.go
- internal/brokers/broker_test.go
- internal/brokers/export_test.go
- internal/brokers/testdata/TestIsAuthenticated/golden/adds_default_groups_even_if_broker_did_not_set_them
- internal/brokers/testdata/TestIsAuthenticated/golden/error_when_broker_returns_userinfo_with_mismatching_username
- internal/brokers/testdata/TestIsAuthenticated/golden/error_when_calling_isauthenticated_a_second_time_without_cancelling
- internal/brokers/testdata/TestIsAuthenticated/golden/no_error_when_broker_returns_userinfo_with_empty_gecos
- internal/brokers/testdata/TestIsAuthenticated/golden/no_error_when_broker_returns_userinfo_with_group_with_empty_ugid
- internal/brokers/testdata/TestIsAuthenticated/golden/successfully_authenticate
- internal/brokers/testdata/TestIsAuthenticated/golden/successfully_authenticate_after_cancelling_first_call
- internal/services/pam/pam_test.go
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_on_updating_local_groups_with_unexisting_file/IsAuthenticated
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_when_broker_returns_username_different_than_the_one_selected/IsAuthenticated
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_when_broker_returns_username_different_than_the_one_selected/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/error_when_calling_second_time_without_cancelling/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/successfully_authenticate/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/successfully_authenticate_if_first_call_is_canceled/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/update_existing_db_on_success/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/update_local_groups/cache.db
- internal/services/pam/testdata/TestIsAuthenticated/golden/update_local_groups/gpasswd.output
- internal/testutils/broker.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/deny_authentication_if_usernames_dont_match
- pam/integration-tests/testdata/tapes/mismatch_username.tape
The broker could return a username different from what was selected locally and the authentication would be granted. To prevent this from happening, we should check if the username returned by the broker is the same as the one first selected in PAM.
UDENG-2515
> feat: Validate username returned by the broker

- internal/services/pam/pam_test.go
- internal/services/permissions/permissionstests/permissionstests.go
- internal/services/permissions/testutils.go
Based on the fact that the property being mutated is dependent on `currentUserAsRoot`, I believe the method name needs adjustment.
> fix(services): Renaming  [Ss]etCurrentRootAsRoot => [Ss]etCurrent**User**AsRoot

- go.mod
- tools/go.mod
Bump Go to 1.22.3
Fixes Vulnerability #1: GO-2024-2824
Malformed DNS message can cause infinite loop in net
More info: https://pkg.go.dev/vuln/GO-2024-2824
Found in: net@go1.22.2
Fixed in: net@go1.22.3
> maint: vulnerability fix in net module

- nss/integration-tests/helper_test.go
- nss/integration-tests/integration_test.go
We used to check the error returned by the execution of the subprocess. We are now checking if the getent command is returning the expected status code.
The `getent` command can have 4 possible status codes:
0 - Success;
1 - Missing arguments, or database unknown; (We don't care about this one, since it's a command misusage and has nothing to do with our module)
2 - One or more supplied keys could not be found in the database; (This is what we expect to receive in all of our error cases)
3 - Enumeration is not supported on this database. (Not sure what this one means, but I don't think it matters to us)
UDENG-2693
> tests: Update NSS integration tests expected error output

- Cargo.lock
Dependabot only updates the direct dependencies listed in `Cargo.toml`. This results (especially if they rely "too much" on SemVer) in some of our transitive dependencies (i.e. dependencies of our dependencies) being outdated in `Cargo.lock`.
> deps(rust): Bump NSS crate transitive deps to latest versions

- pam/go-exec/module.c
- pam/integration-tests/cmd/exec-client/client.go
- pam/main-exec.go
Even though the server will only allow connections from a specific PID (the one that it launched), it's still better not to expose infos that could give hint to potential attackers
UDENG-2831
> pam/go-exec: Expose the server address using an env variable

- go.mod
- tools/go.mod
Fixes Vulnerability #1: GO-2024-2887
The various Is methods (IsPrivate, IsLoopback, etc) did not work as expected
for IPv4-mapped IPv6 addresses, returning false for addresses which would
return true in their traditional IPv4 forms.
More info: https://pkg.go.dev/vuln/GO-2024-2887
Found in: net@go1.21.0
Fixed in: net@go1.22.4
> maint: Bump go to 1.22.4 to fix vulnerability in net module

- .github/workflows/qa.yaml
Use both job id and the attempt so that we don't risk overwriting the previous values
This should avoid uploading artifacts failures such as in https://github.com/ubuntu/authd/actions/runs/9367176490/job/25786282242
> ci: Use unique names for artifacts names

- cmd/authd/integrationtests.go
- internal/users/localgroups/localgroups_test.go
- internal/users/localgroups/testutils/gpasswd.go
- nss/integration-tests/integration_test.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/gdm_test.go
Pass mock control as arguments and not env variable
This allows use to better alignement with the rest of our mock behaviour control, without relying on internal env variable.
Those are now the first arguments for the mock, after -- and before the arguments passed to the cmdline itself.
Strip them to the cmdline.
UDENG-2955
> No env for gpasswd mock

- pam/go-exec/module.c
Using strings can be dangerous in case something changes, plus we are doing string comparisons for some actions that can be handle better with a switch.
Just few cleanups I noticed...
> pam/pam-exec: Use an enum for the action types

- internal/daemon/daemon_test.go
- internal/testutils/daemon.go
Fix some issues I got while building packages both locally (with sbuild, that as per commit 4a98eca runs as fakeroot) and in the PPA, mostly due to builders not being fast enough when spawning lots of parallel tests.
See failures: 
- https://launchpad.net/~3v1n0/+archive/ubuntu/authd/+build/28517439
- https://launchpad.net/~3v1n0/+archive/ubuntu/authd/+build/28517440
UDENG-3044
> fix(tests): Handle failures during debian packaging builds

- pam/go-exec/module.c
- pam/integration-tests/exec_test.go
If opening the log file fails, we may try to warn while we're still holding the logger lock file, causing a deadlock.
Fix this and add a test ensuring we're covered by this.
> pam/go-exec: Fix a deadlock that happens if an invalid logpath is provided

- pam/internal/adapter/authmodeselection.go
The additional code entry in the layout must be optional, not required. Otherwise, this invalidates QR Codes with no code associated with them.
> fix(pam): Fix supported UI layout for the QR Code

- internal/users/cache/db_test.go
- internal/users/cache/testdata/TestUpdateUserEntry/golden/update_user_by_changing_attributes
- internal/users/cache/testdata/TestUpdateUserEntry/golden/update_user_does_not_change_homedir_if_it_exists
- internal/users/cache/update.go
We used to update every part of the user information in the cache but this can create problems if the admin changes the homedir configuration on the broker side, since it would update the homedir parsing for the user resulting in PAM creating a new one for the user at login.
UDENG-3125
> fix(cache): Do not change homedir for user that already exists

- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_with_mfa
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/change_passwd_after_mfa_auth
- pam/internal/adapter/nativemodel.go
> pam/nativemodel: Fix typo on auth selection screen due to strings joining

- nss/src/group/mod.rs
- nss/src/passwd/mod.rs
- nss/src/shadow/mod.rs
NSS error messages lacked useful information due to missing data on the GRPC error. This improves the messages by a considerable amount by printing the actual value the module is querying for and the return status of the request.
Now we go from messages like:
```
authd: error when getting passwd by name:
```
To:
```
authd: error when getting passwd by name 'nonexistent': Some requested entity was not found
```
UDENG-3410
> fix(nss): Improve NSS error logs

- debian/pam-configs/authd.in
Authd was not registered by pam-auth-update automatically due to the comment which is unsupported by this tool.
One a blank machine, which never got the request, this will now enable it by default.
There is no format supporting comments unfortunately after reading the upstream perl source.
UDENG-3408
> fix: remove comment from authd pam module to make it enable by default

- debian/pam-configs/authd.in
Authd has a high priority in the PAM stack. When we don’t ignore on purpose the authentication to pass to other modules, we should fail immediately it.
We thus mirror requisite with still allowing the none authentication access part to be skipped.
UDENG-3413
> fix: ensure we fail authentication when user auth failed

- pam/integration-tests/cli_test.go
Since commit d1a75d811, for the cli tests we call prepareClientTest() for each test in order to get the client folder, however this also implies building the test client, the module and the exec client for each test even though this is not needed, since we can share those binaries.
So just call this once in the main test.
Ideally this should make CI a little quicker.
> cleanup(pam/integration-tests/cli): Do not build the module and pam clients for each test

- nss/src/group/mod.rs
- nss/src/passwd/mod.rs
- nss/src/shadow/mod.rs
As in the documentation:
/// If you only need description in `println`, `format`, `log` and other
/// formatting contexts, you may want to use `Display` impl for `Code`
/// instead.
So, let’s use the display trait as the error macro is using format.
Note that this is prior the logging refactoring.
> fix: do not explicitly call description on nss error

- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_with_qr_code
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_with_qr_code_in_a_tty
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_with_qr_code_in_a_tty_session
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_with_qr_code_in_screen
- pam/internal/adapter/qrcodemodel.go
In some cases (e.g. small terminals, tty's) the qrcode is not properly
rendered or is not fully visible, so make the URI to be always written
so that it can be used also without a qrcode scanner
UDENG-3324
> feat(qrcodemodel): Always include the content URI to the output

- nss/src/group/mod.rs
- nss/src/logs/mod.rs
- nss/src/passwd/mod.rs
- nss/src/shadow/mod.rs
That way, we don’t spam logs for 3rd party applications using our library as they are the one which should control the output to the user. We send back those errors in a NSS format anyway to the caller already.
We thus only print details when AUTHD_NSS_INFO=stderr is set.
UDENG-3409
> maint: downgrade NSS lib errors to info

- examplebroker/broker.go
- pam/integration-tests/gdm-module-handler_test.go
- pam/integration-tests/gdm_test.go
- pam/internal/adapter/gdmmodel.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/gdmmodel_uimodel_test.go
- pam/internal/gdm/extension.go
- pam/internal/gdm_test/gdm_utils.go
- pam/internal/pam_test/pam-client-dummy.go
Ensure `reselectAuthMode` is properly handled by the gdm model, following what the others model do
UDENG-3126
> fix(pam/gdm): Fix and test handling of gdm qrcode regeneration

- nss/src/passwd/mod.rs
The cmdline returned by calling proc.cmdline() has multiple strings that consist of the entire command, which means that, instead of having something like this: ["cmd", "arg1", "arg2, ..., "argn"] It looks like this: ["cmd arg1 arg2 ... argn"]
In order to better limit the options, as this precheck can be a security breach, we only allow the precheck if it comes from the common known sshd binary.
UDENG-3415
> fix(NSS): Fix should_pre_check logic to identify sshd

- pam/integration-tests/testdata/tapes/cli/mfa_auth.tape
The test is quite unreliable [1] when running in CI or under pressure, so let's see if we can make it more stable by increasing the wait times, until vhs will support officially the wait feature.
[1] https://github.com/ubuntu/authd/actions/runs/9765222175/job/26955414933
UDENG-3549
> pam/integration-tests/cli: Increase the wait times on MFA test

- examplebroker/broker.go
- pam/integration-tests/gdm_test.go
- pam/integration-tests/testdata/TestCLIChangeAuthTok/golden/retry_if_new_password_is_rejected_by_broker
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/retry_if_new_password_is_rejected_by_broker
- pam/integration-tests/testdata/tapes/cli/passwd_rejected.tape
- pam/integration-tests/testdata/tapes/native/passwd_rejected.tape
- pam/internal/adapter/authentication.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/nativemodel.go
- pam/internal/adapter/newpasswordmodel.go
- pam/internal/pam_test/pam-client-dummy.go
Support checking for password quality when logging-in with GDM, due to the nature of GDM model, we can only provide the final check after the user as typed the password twice, but that's still better than not having the check at all.
To keep the GDM model agnostic to the change, handle this only in the `authentication` backend, so that in the gdm case it's also doing an extra step to check the challenge before passing the data to the broker.
Add tests to handle the newpassword layout in gdm, since we had not them yet.
UDENG-3374
> feat(pam/gdmmodel): Add support for password quality check

- .github/workflows/qa.yaml
- debian/control
- pam/integration-tests/gdm_test.go
- pam/internal/adapter/gdmmodel_test.go
In order to do password dictionary checks we need to use cracklib, but the runtime isn't installed by default in debian so add a test dependency for it and, just in case, to debian too.
Also use the simplest password ever that would fail any dictionary check (and that's part of cracklib's cracklib-small dictionary)
It built fine at https://launchpad.net/~ubuntu-enterprise-desktop/+archive/ubuntu/authd/+sourcepub/16261392/+listing-archive-extra
UDENG-3575
> fix(debian): Add pwquality dictionary check dependencies

- internal/services/pam/pam.go
- internal/services/pam/pam_test.go
When we only have the local broker available, autoselect it for unknown users.
Current implementation is temporarly and will be removed for v2, as this will be all internal to authd.
UDENG-3411
> feat: local broker preselection for unknown user when only local broker available

- examplebroker/broker.go
- pam/integration-tests/cmd/exec-client/modulewrapper.go
- pam/integration-tests/native_test.go
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_on_ssh_service
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_on_ssh_service_with_custom_name_and_auth_info_env
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_on_ssh_service_with_custom_name_and_connection_env
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/exit_if_user_is_not_pre-checked_on_custom_ssh_service_with_auth_info_env
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/exit_if_user_is_not_pre-checked_on_custom_ssh_service_with_connection_env
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/exit_if_user_is_not_pre-checked_on_ssh_service
- pam/integration-tests/testdata/tapes/native/local_ssh.tape
- pam/integration-tests/testdata/tapes/native/simple_ssh_auth.tape
- pam/internal/adapter/model.go
- pam/internal/adapter/nativemodel.go
- pam/main-cli.go
- pam/pam.go
When the PAM module is loaded by SSHd we may not want to expose broker
information to everyone that is connecting, so if the user is not known
by any broker we should just not give the ability to even select the
broker but to just auto-select the local broker instead
UDENG-3600
> fix(pam/nativemodel): Select local broker if user does not exist on SSH connection

- debian/postinst
The debian/postrm script removes authd as a source from /etc/nsswitch.conf, but the debian/postinst script only added it when the package was installed for the fist time. That led to NSS not using authd as a source when the package was reinstalled.
We now ensure that authd is always added as a source to the `passwd`, `group` and `shadow` databases in /etc/nsswitch.conf when the authd package is installed.
UDENG-3906
> debian: Also insert authd as NSS source on reinstall

- internal/brokers/dbusbroker.go
- internal/brokers/manager_test.go
We now have a wrapper around the dbus calls to be able to intercept the errors and format the messages in a way that is helpful to end user. This helps avoiding error messages that are too technical, such as "the object X was not provided by any .service files" which is returned when the broker is not available on DBus.
UDENG-4094
> Rework dbusbroker dbus calls to format errors

- nss/integration-tests/integration_test.go
- nss/integration-tests/testdata/db/pam_unix_non_existent.db.yaml
- nss/src/passwd/mod.rs
This is a common call done by PAM to prevent attacks. We need to special case it to avoid spamming the system logs with Not Found messages when the call happens.
Closes #468.
UDENG-3934
> Ignore pam_unix_non_existent on getpwnam calls

- pam/integration-tests/testdata/tapes/cli/qr_code.tape
- pam/integration-tests/testdata/tapes/cli/qr_code_quick_regenerate.tape
- pam/internal/adapter/qrcodemodel.go
When hitting the Enter key for a while, bubbletea sends lots of events and we may imply sending reselectAuthMode{} events faster than we can actually handle the cancellation/reauthModeSelection in the whole stack.
This never happened (ever) when using the example broker, but it may actually happen in a real world scenario where the broker may not cancel the requests quickly enough.
Do this instead of avoiding the handling of the reselectAuthMode event because it's better to prevent bubbletea to break our (fragile) system.
The change is already tested by `authenticate_user_with_qr_code_after_many_regenerations` test.
UDENG-4091
> qrcodemodel: Rate limit the emission of reselect auth mode events

- .golangci.yaml
golangci-lint complained:
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
> Replace deprecated linter 'exportloopref' with 'copyloopvar'

- internal/users/cache/db.go
- internal/users/cache/db_test.go
- internal/users/cache/testdata/TestCleanExpiredUsers/golden/do_not_clean_active_user
- internal/users/cache/testdata/active_user.db.yaml
- internal/users/cache/testutils.go
- internal/users/manager.go
I've encountered a case where each `getpwuid` call took 5 seconds, and because there were a lot of active processes from an orphaned user, we issued so many `getpwuid` calls that the start operation of the authd.service timed out. 
Closes #542
UDENG-4628
> Don't try to get passwd entry for UIDs which we know are orphaned

- pam/integration-tests/native_test.go
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_with_qr_code_in_ssh
- pam/internal/adapter/nativemodel.go
- pam/internal/adapter/utils.go
- pam/pam.go
Do not renderer qrcode in SSH at all, the only clients supporting it are putty and `ssh` provided by ubuntu (>= 24.04), and it's not possible (yet) to detect this from PAM level, so let's just ignore it for now.
And add an integration test covering this case.
Closes: #497 
UDENG-4279
> pam/native-model: Do not render qr code in SSH sessions at all

- internal/users/manager.go
See https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes
Closes #547
UDENG-4689
> Use UID/GID range that doesn't overlap with the range used by Debian

- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_max_attempts_reached
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/prevent_change_password_if_auth_fails
- pam/internal/adapter/nativemodel.go
In case that the authentication failed, the authentication model sends a pamError that includes the error message and that our pam module will eventually write.
So, there's no need to handle the error again in the native module or we'd duplicate such error string
UDENG-4763
> fix(pam/nativemodel): Do not report the authentication denied PAM error twice

- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_switching_to_local_broker
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_with_mfa_and_reset_password_while_enforcing_policy
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_current_user_is_not_considered_as_root
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_max_attempts_reached
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_newpassword_does_not_match_required_criteria
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_user_does_not_exist
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/prevent_change_password_if_auth_fails
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/prevent_change_password_if_current_user_is_not_root_as_can't_authenticate
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/prevent_change_password_if_user_does_not_exist
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/retry_if_new_password_does_not_match_quality_criteria
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/retry_if_new_password_is_rejected_by_broker
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/retry_if_new_password_is_same_of_previous
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/retry_if_password_confirmation_is_not_the_same
- pam/main-cli.go
Ensure they're clearly marked as such so that we don't confuse them with simple info messages.
> cleanup(pam/integration-tests): Highlight PAM error messages better

- pam/integration-tests/native_test.go
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_user_does_not_exist_and_matches_cancel_key
- pam/integration-tests/testdata/tapes/native/cancel_key_user.tape
This is something that was already manually tested, but since 'r' is a special string in the native model, let's add an explicit check, ensuring that a such user can work properly.
And no, we won't support a 'r' secret, even though we could just wait for a broker refusal before using it as a "go back" command, but at the date there's not a real requirement for that to increase the model complexity.
> pam/integration-tests/native: Check that the user 'r' is accepted

- .github/workflows/qa.yaml
- pam/integration-tests/cmd/exec-client/client.go
- pam/integration-tests/exec_test.go
- pam/integration-tests/gdm_test.go
- pam/integration-tests/helpers_test.go
Passing lots arguments to a pam library via the service file is not very much supported by older libpam libraries as the one we've in CI, so avoid failing on that by passing the same arguments to the exec-test client through a file when required.
---
This was already approved
UDENG-4793
> fix(pam/integration-tests): Fix potential failures depending on pam arguments

- examplebroker/broker.go
We had a data race, since we were accessing to the isAuthenticatedCalls map without locking, fix this avoiding lock/unlock dance.
```
WARNING: DATA RACE
Read at 0x00c0001a03f0 by goroutine 311:
runtime.mapaccess2_faststr()
/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/map_faststr.go:117 +0x0
github.com/ubuntu/authd/examplebroker.(*Broker).EndSession()
/home/runner/work/authd/authd/examplebroker/broker.go:733 +0xf9
github.com/ubuntu/authd/examplebroker.(*Bus).EndSession()
/home/runner/work/authd/authd/examplebroker/dbus.go:115 +0x5b
runtime.call32()
/opt/hostedtoolcache/go/1.23.0/x64/src/runtime/asm_amd64.s:776 +0x42
reflect.Value.Call()
/opt/hostedtoolcache/go/1.23.0/x64/src/reflect/value.go:365 +0xb5
github.com/godbus/dbus/v5.exportedMethod.Call() …
```
> fix(examplebroker): Use locked access to isAuthenticatedCalls on end session

- pam/internal/adapter/gdmmodel.go
- pam/internal/gdm/conversation.go
- pam/internal/gdm/debug.go
- pam/internal/gdm/export_test.go
- pam/internal/gdm/protocol.go
Instead of hiding the content authentication data completely, show the
whole challenge when `pam_gdm_debug` build tag is used, or when in
testing mode.
Otherwise, just show a sanitized challenge so that we don't miss the
fact that the event has happened.
In the same way, keep the conversation debugging alive so that we don't miss pieces of what we got from GDM if the content is relevant.
To sanitize the JSON I preferred to go wild and just replace the content, since it's still something happening only when debugging only, so not really something in production code.
Fixes: ca47562d3153, 40fa85db968ff
> pam/gdm: Keep debugging all the events, sanitizing them if needed

- pam/internal/adapter/pwquality_c.go
In some tests we are failing withe errors such as:
- The password fails the dictionary check - error loading dictionary
This is likely due to the fact that we're accessing to the data from multiple threads, while the library doesn't seem to be thread-safe so add a mutex to ensure this
> maint(pam/pwquality): Protect access to pwquality calls with a mutex

- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/model.go
See each commit for details, but this comes up to fix races such as https://github.com/ubuntu/authd/actions/runs/11325604248/job/31492851219 where we may end up doing duplicate requests to `GetAuthenticationModes` that eventually lead to two `selectAuthMode(firstAuthModeID)` which may break our "go-back" requests.
Also simplify the handling of `supportedUILayouts` so that it's following more the ELM architecture.
This implies that no broker requests is done until we've the supported UI defined now, but it's definitely a prerequisite to continue, so making this more explicit looks cleaner to me.
UDENG-4943
> fix(pam): Avoid duplicate auth-mode selection race

- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/model.go
We didn't care about checking broker details on error, but we where just
ignoring all the Pam.ErrSystem's instead of only the ones due to a test
early stop request.
So fix this, fixing various test races:
-  https://github.com/ubuntu/authd/actions/runs/11332985482/job/31516241957
- https://github.com/ubuntu/authd/actions/runs/11332985482/job/31517065552
> pam/gdmmodel-test: Ignore brokers checks on PAM errors

- .github/workflows/qa.yaml
Use a GitHub Action which caches the grcov binary installed via cargo install.
> ci: Cache grcov installed via cargo install

- pam/integration-tests/cli_test.go
- pam/integration-tests/gdm_test.go
- pam/integration-tests/native_test.go
We were running a new authd instance for each gdm test, but this is not
needed anymore as we're using unique user names (since commit 7a77d331),
so let's just add more concurrency to the game, ensuring that authd is
still behaving well when multiple requests are happening concurrently
with gdm too
> maint(pam/integration-tests/gdm): Use unique authd instance for gdm tests

- examplebroker/com.ubuntu.auth.ExampleBroker.xml
"a{s}s" is not a valid GVariant type, it should be "a{ss}" instead.
> Fix example broker D-Bus XML file

- cmd/authd/daemon/config.go
- cmd/authd/main.go
- go.mod
- internal/consts/consts.go
- internal/log/log.go
- internal/log/log_test.go
- internal/services/errmessages/redactor.go
- internal/services/manager.go
- internal/users/cache/delete.go
- internal/users/cache/update.go
- internal/users/localgroups/localgroups.go
- internal/users/manager.go
Currently, we use both our own github.com/ubuntu/authd/internal/log package (with logrus as the backend) and log/slog in authd. We want to use slog as the backend for out custom log package and consistently use that (instead of mixing uses of the custom log package and direct uses of slog).
UDENG-4622
> Replace logrus with slog

- pam/integration-tests/testdata/TestNativeAuthenticate/golden/deny_authentication_if_current_user_is_not_considered_as_root
- pam/integration-tests/testdata/TestNativeChangeAuthTok/golden/prevent_change_password_if_current_user_is_not_root_as_can't_authenticate
- pam/integration-tests/testdata/tapes/native/not_root.tape
- pam/integration-tests/testdata/tapes/native/passwd_not_root.tape
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/model.go
- pam/internal/adapter/userselection.go
One of the races we were facing (mostly in native model) is that we
could end up in a situation in which we receive an authd error on
getting the brokers list *after* that the user selection view is already
shown, leading to racy golden files ordering.
This is because what it could happen is:
- We start in parallel:
-> User selection
-> UI Layouts -> Available brokers fetching
Now let's "imagine" that the brokers fetching fails (as when we've not
the permissions to read it, as for being not root).
If the user selection result arrives first, then we end up showing the
user selection UI (that is blocking in the native model) and only then
we handle the AvailableBrokers result (the error).
If the broker selection arrives first, we show first the error instead.
Now, this kind of approach made …
> fix(pam/model): Initialize user only after we've got the brokers list

- pam/internal/adapter/userselection.go
When the model is not enabled we may still have it focused, since it's the default initial model that we have in the CLI mode.
This may cause to a visual issue (not a security one, since the input is disabled for this):
- login with the UI using a preset user
- while the client is connecting to the server we may show a "frozen" user selection view with the pre-selected  user written in.
This is not really something we need to show, so do not draw anything until we've something to show.
This can be replicated easily by applying:
```diff
diff --git a/pam/internal/adapter/brokerselection.go b/pam/internal/adapter/brokerselection.go
index 54725222..31c56f7b 100644
--- a/pam/internal/adapter/brokerselection.go
+++ b/pam/internal/adapter/brokerselection.go
@@ -5,6 +5,7 @@ import (
"fmt"
"io" …
```
> pam/userselection: Do not draw the model when not enabled

- pam/integration-tests/gdm-module-handler_test.go
- pam/integration-tests/gdm_test.go
We have some races in gdm tests caused by the fact we may send the
`brokerSelected` event too late, in particular when we received the
broker list, but at that point we may be have done other steps already.
Instead, handle the broker selection only when we're in broker selection
stage, and not too early or too late.
> fix(pam/integration-tests/gdm): Handle broker selection when on such stage

- .github/workflows/qa.yaml
- tools/gotestfmt
The output of go test is notoriously hard to read, especially when a lot of tests are executed and a lot of output is produced, which is the case in our CI.  This commit uses gotestfmt to format the go test output. It only prints the output of failed tests to stdout, because that's what we're usually interested in. In case we need the full test output, that's now uploaded as an artifact.
You can see an example of the produced output when a test fails in [this job](https://github.com/ubuntu/authd/actions/runs/11635771849/job/32405830353?pr=608). The produced artifacts for that job are available [here](https://github.com/ubuntu/authd/actions/runs/11635771849/artifacts/2134799888) or when you scroll down on the [summary page](https://github.com/ubuntu/authd/actions/runs/11635771849?pr=608) …
> ci: Use gotestfmt to format go test output

- pam/internal/adapter/gdmmodel.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/model.go
authModeSelected event we were listening to is an event that may be
ignored or adjusted depending on authModeSelection model logic, so it's
what we should also expose to GDM.
We couldn't do that though since the event wasn't forwarded, so do it.
Also simplify user selection on GDM tests, by mimicking more what we really do.
It should help with flacky tests such as [1].
[1] https://github.com/ubuntu/authd/actions/runs/11802896113/job/32879602555?pr=583
> fix(pam/gdmmodel): Forward public AuthModeSelected to GDM

- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/gdmmodel_uimodel_test.go
Do not send the authentication data too early as we may not be in the
challenge stage yet.
Fixes races that we're seeing when optimizing constants: [1]
[1] https://github.com/ubuntu/authd/actions/runs/11835831306/attempts/1
UDENG-5261
> fix(pam/gdmmodel-test): Send authentication data only if in challenge stage

- CONTRIBUTING.md
- docs/conf.py
- docs/explanation/authd-architecture.md
- docs/explanation/index.md
- docs/howto/configure-authd.md
- docs/howto/index.md
- docs/howto/install-authd.md
- docs/howto/login-gdm.md
- docs/howto/login-ssh.md
- docs/index.md
Improves some aspects of authd docs on Read the Docs that affect User Experience:
* Adds feedback button: this allows one-click generation of GitHub issue with template
* Better grid navigation on homepage: links are fixed and any region of card can now be clicked as a link
* Consistent use of name “authd”: always lowercase
* Accessibility: adds alt text to images
UDENG-5360
> docs: UX fixes for RTD docs

- .github/workflows/qa.yaml
If no `if` conditional is specified, a step is only executed if all previous succeeded (i.e. it defaults to `if success()`), see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions
> Fix artifacts not uploaded on failure

- internal/services/pam/pam_test.go
- internal/users/cache/db_test.go
- internal/users/cache/testutils.go
- internal/users/cache/testutils/serialization.go
- internal/users/manager_test.go
I was surprised that "DumpToYaml" modifies some values in the returned YAML. The new name should be less surprising.
It also contains the acronym YAML in uppercase, as recommended by the Go Code Review Comments: https://go.dev/wiki/CodeReviewComments#initialisms
Also improves the doc comment of the function.
UDENG-5450
> refactor: Rename DumpToYaml -> DumpNormalizedYAML

- examplebroker/broker.go
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/authenticate_user_with_form_mode_with_button
- pam/integration-tests/testdata/TestCLIAuthenticate/golden/remember_last_successful_broker_and_mode
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/authenticate_user_with_form_mode_with_button
- pam/integration-tests/testdata/TestNativeAuthenticate/golden/remember_last_successful_broker_and_mode
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/authenticate_user_switching_auth_mode_on_shared_sshd
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/authenticate_user_with_form_mode_with_button
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/authenticate_user_with_form_mode_with_button_on_shared_sshd
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/remember_last_successful_broker_and_mode
- pam/integration-tests/testdata/TestSSHAuthenticate/golden/remember_last_successful_broker_and_mode_on_shared_sshd
- pam/internal/adapter/authentication.go
- pam/internal/adapter/button.go
- pam/internal/adapter/formmodel.go
- pam/internal/adapter/newpasswordmodel.go
- pam/internal/adapter/qrcodemodel.go
- pam/internal/adapter/reselectbuttonmodel.go
Prevent the user to do too-many auth mode reselections that may lead to break the broker.
Cleans up https://github.com/ubuntu/authd/pull/513 by adapting the same logic to the other models too.
UDENG-5520
> cleanup(pam): Use the same logic for the re-selection button event

- internal/users/localgroups/testutils/gpasswd.go
I'm not sure why, but since 48eb235d845ff4c717eea6111153b44048239bc4 golangci-lint fails with:
internal/users/localgroups/testutils/gpasswd.go:3:1: directive `//nolint:gci // We import unsafe as it is needed for go:linkname, but the nolint comment confuses gofmt and it adds` is unused for linter "gci" (nolintlint)
Removing that line fixes it.
> Fix golangci-lint complaint

- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/migration.go
- cmd/authd/daemon/migration_test.go
- debian/authd.service.in
- internal/consts/consts.go
- internal/fileutils/fileutils.go
- internal/fileutils/fileutils_test.go
The database is not a cache, removing it has an impact on security because it allows users to be assigned the UID of a previous user.  
We reflect that by storing the database in `/var/lib/authd/` instead of `/var/cache/authd/`.
> Change database dir from /var/cache/authd/ to /var/lib/authd/

- README.md
- SECURITY.md
The authd docs have been migrated from the GH wiki to Read the Docs.
This PR updates links to the documentation in the README.md and SECURITY.md .
In addition, a docs badge (build pass/fail) was added to the README.md.
Other minor changes:
- Removed capitalisation in first letter of authd for consistency of branding
- Reduced direct links to doc pages in README (maintenance issue at this stage in the docs development)
- Shortened line lengths in README (for source readability)
UDENG-5515
> docs: Update README and SECURITY for docs migration

- internal/brokers/manager.go
- internal/services/pam/pam.go
- internal/services/pam/pam_test.go
- pam/pam.go
The decision whether to use the local broker or not should be made on each login request, based on whether the user exists locally or not. If we cache that decision, the local broker is used even when the local user was removed.
UDENG-5338
> Fix local broker being used after local user was removed

- debian/authd.service.in
We only migrate the old database directory if the new one doesn't exist, so we shouldn't let systemd automatically create it.
This reverts commit f68935530c130a249dbdc340d475907728ed2d57.
> Fix broken db migration because new db dir always exists

- debian/changelog
* Change database directory from /var/cache/authd to /var/lib/authd.
The database is not a cache, removing it has an impact on security
because it allows users to be assigned the UID of a previous user
This is now reflected by storing the database below /var/lib instead
of /var/cache.
* Fix user being removed from local groups during login
* Fix defaulting to local broker even after local user is removed
* API: Support exposing if the UI supports QR code rendering
* PAM module:
* Fix races
* Many small fixes
* Update dependencies
> Add changelog entry for 0.3.7

- cmd/authd/daemon/daemon_test.go
- internal/brokers/manager_test.go
- internal/services/manager_test.go
- internal/services/nss/nss_test.go
- internal/services/pam/pam_test.go
- internal/users/localgroups/localgroups_test.go
- internal/users/manager_test.go
- nss/integration-tests/integration_test.go
- pam/integration-tests/cli-integration_test.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/dbusmodule/transaction_test.go
- pam/internal/pam_test/pam-client-dummy_test.go
This is not needed since Go 1.15, where the test runtime registers the test result itself.
Also, os.Exit() would skip any defer() being called before, which might pollute the system running the tests.
Note that we only kept 2 occurences when subprocessing as a mock, as we shouldn't expect to have defer() beforehand in TestMain.
UDENG-5632
> Remove incorrect os.Exit(m.Run()) calls

- debian/pam-configs/authd.in
- If authd ignored the request, then we should ignore too.
- If we can't connect to authd, we should ignore to select next method.
- If we fail hard for other reason, then user should not be authenticated.
Removed the handling of user_unknown case because we never return this from the PAM module for security reasons.
UDENG-5636
> debian/pam-configs/authd: Ignore connection errors

- pam/internal/adapter/commands.go
- pam/internal/adapter/return.go
- pam/pam.go
As per commit 4fd03a407e69 we're just not storing if the local broker
has been used, as per this we don't even care about saving it in the
module since we'd just return with pam.ErrIgnore anyways if the broker
authentication ID isn't stored or is null
Thus we don't need to return anymore the ID of the local broker if we
want to be used, so we can also remove the complexity of
PamIgnore, by just considering it a particular case of pamError
UDENG-5576
> pam: Do not save or check for local broker ID in module data and drop PamIgnore

- docs/howto/configure-authd.md
IAM-1259
This PR adds the new device ownership changes that are described in UD084 and introduced by https://github.com/ubuntu/authd-oidc-brokers/pull/249. I could not find any reference docs or any information about non-entraID providers, the `broker.conf.d` folder or any of the other configuration sections. Please let me know if you think that I should add info somewhere else as well.
cc @adombeck @edibotopic
> Add device ownership configuration docs

- docs/howto/configure-authd.md
The device ownership feature has not been released yet.
This reverts commit 4ed5bd4e0940142e975faa2ba8a554600bdf314f.
> docs: Remove device ownership docs

- .github/workflows/qa.yaml
The diffs of mismatching golden files are passed through git-delta since https://github.com/ubuntu/authd/pull/645.
> ci: Install git-delta for nicer diffs in error messages

- internal/errno/errno_c.go
- internal/errno/errno_c_test.go
- internal/errno/export_test.go
- pam/integration-tests/vhs-helpers_test.go
- pam/tools/pam-runner/pam-runner.go
See commits for details.
Close: #703
UDENG-5710
> tests: Handle some failures when using -race

- README.md
- docs/index.md
- docs/reference/troubleshooting.md
The authd docs now include `stable` and `latest` versions.
The `stable` points to that last tagged release (excluding alphas and betas) and is the default.
The `latest` points to the last commit in the main branch and can be toggled in the dialog on the bottom right of each page:
Helpfully, when a user switches to `latest`, Read the Docs shows a notification that some features that are documented may not be available in the stable release:
Despite these affordances, it is still a good idea to mention explicitly that there are two versions of the docs, providing links where appropriate.
Main changes here are:
* updating README docs links to include stable and latest
* adds comment on docs versions to README and docs homepage
* adds comment on latest docs in troubleshooting section that …
> docs: add references to stable and latest docs versions

- go.mod
- pam/internal/adapter/nativemodel.go
- pam/internal/adapter/utils.go
- pam/pam.go
In case a PAM tty is used, we should do our terminal checks against that
instead of the stdin value, since they may differ.
Do this check also to ensure that we can run the interactive CLI UI.
A follow-up of https://github.com/ubuntu/authd/pull/720#discussion_r1910410356
UDENG-5760
> pam: Always Honor PAM_TTY if set

- examplebroker/broker.go
I don't remember why I removed those. Let's try reverting the change.
This partly reverts 7a1442fbf3becf374947b4f443f1b1eb12c9da17.
> Revert removal of groups in example broker

- .github/workflows/build-deb.yaml
- debian/changelog
- debian/copyright
- debian/get-depends-go-bin-path.sh
- debian/rules
- debian/tests/run-tests.sh
Add a workflow to build debian packages and run autopkgtests.
Requires: https://github.com/canonical/desktop-engineering/pull/58 
UDENG-2343
> CI: Build debian packages and run autopackage tests

- debian/authd.service.in
- debian/postinst
Fixes two warnings caused by the changes made to the systemd service definition:
```
authd.service: ConfigurationDirectory 'authd' already exists but the mode is different. (File system: 755 ConfigurationDirectoryMode: 700)
```
and 
```
Both old and new database directories exist, can't migrate "/var/cache/authd/" to "/var/lib/authd/"
```
UDENG-5857
UDENG-5858
> Fix systemd service warnings

- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code_in_a_TTY
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code_in_a_TTY_session
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code_in_polkit
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code_in_screen
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_qr_code_in_ssh
- pam/integration-tests/testdata/golden/TestSSHAuthenticate/Authenticate_user_switching_auth_mode
- pam/integration-tests/testdata/golden/TestSSHAuthenticate/Authenticate_user_switching_auth_mode_on_shared_SSHd
- pam/integration-tests/testdata/golden/TestSSHAuthenticate/Authenticate_user_with_qr_code
- pam/integration-tests/testdata/golden/TestSSHAuthenticate/Authenticate_user_with_qr_code_on_shared_SSHd
- pam/internal/adapter/nativemodel.go
When using the qr code mode we may actually just require a login code, so instead on hardcoding the labels binding them to the qrcode case, let's just use what the broker provides us.
Closes: #755
UDENG-5862
> pam/nativemodel: generalize the qrcode labels

- go.mod
- tools/go.mod
govulncheck reports the following vulnerability in crypto/x509@go1.23:
```
Vulnerability #1: GO-2025-3373
Usage of IPv6 zone IDs can bypass URI name constraints in crypto/x509
More info: https://pkg.go.dev/vuln/GO-2025-3373
Found in: crypto/x509@go1.23
Fixed in: crypto/x509@go1.23.5
```
> Bump Go toolchain version to 1.23.5

- .github/ISSUE_TEMPLATE/bug_report.yml
The config files are only readable by root since 9ff0d1a3840db0d1dc46a05cfc260c7d23897ba0 and https://github.com/ubuntu/authd-oidc-brokers/commit/6116ba9c70d0fcae9df197d02c0e1c766d5fc9cd.
> GitHub issue template: Use sudo to collect config file contents

- docs/howto/configure-authd.md
The documentation of the device ownership configuration was revert in https://github.com/ubuntu/authd/pull/704 because back then we didn't have a `latest` version of the docs, so the documentation was already live but the feature was not released yet, which led to confusion of users.
I cherry-picked 4ed5bd4e0940142e975faa2ba8a554600bdf314f, but the "Broker configuration" section which that commit added the new documentation to doesn't exist anymore since 872c99a2797b0333cb228ef2316e3c69abfdd1c, so I added it to a new "Configure allowed users" section instead. 4ed5bd4e0940142e975faa2ba8a554600bdf314f added the full content of the `broker.conf` file to the "Broker configuration" section, which also included the `home_base_dir` and `ssh_allowed_suffixes` options along with their comments, so …
> Add device ownership configuration docs again

- debian/changelog
To be able to upload to Launchpad again. The build of 0.4.0 failed because the XS-Vendored-Sources-Rust value in debian/control, which allowed me to build the package on my host, caused the build to fail on Launchpad.
> Add changelog entry for 0.4.1

- docs/conf.py
- docs/howto/install-authd.md
This PR makes small changes to authd's howto/install guide to improve clarity and consistency:
* **Be more consistent in release language:** The 'stable' release of authd is referred to elsewhere, including the homepage, the README and the PPA page. To be consistent, we should not refer to it as a 'testing' release in the how-to install guide.
* **Try to clearly highlight Desktop and Server offering**: Instead of giving the install commands for Desktop, and then saying some of the packages in that command aren't needed for Server, the specific commands for both cases are now provided in a tabbed interface.  The user can choose the relevant one and copy the appropriate command. That authd can be installed on both systems is also highlighted at the start of the page.
Other minor changes …
> docs: adjust language on releases

- go.mod
govulncheck reports the following vulnerability in nistec@go1.23.5:
```
Vulnerability #1: GO-2025-3447
Timing sidechannel for P-256 on ppc64le in crypto/internal/nistec
More info: https://pkg.go.dev/vuln/GO-2025-3447
Found in: crypto/internal/nistec@go1.23.5
Fixed in: crypto/internal/nistec@go1.23.6
Platforms: ppc64le
```
> Bump Go toolchain version to 1.23.6

- internal/users/manager.go
Log only a single warning with a single `chown` command if both the owner and group are incorrect.
> Improve warning logged when home directory has incorrect owner/group

- examplebroker/broker.go
- examplebroker/users.go
- pam/integration-tests/cli_test.go
- pam/integration-tests/gdm_test.go
- pam/integration-tests/native_test.go
- pam/integration-tests/ssh_test.go
- pam/integration-tests/testdata/golden/TestCLIAuthenticate/Authenticate_user_successfully_with_password_only_supported_method
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_successfully_with_password_only_supported_method
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_form_mode_with_button_in_polkit
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_with_form_mode_with_button_two_supported_methods
- pam/integration-tests/testdata/tapes/native/form_with_button.tape
- pam/integration-tests/testdata/tapes/native/form_with_button_polkit.tape
- pam/internal/adapter/nativemodel.go
Polkit UI is quite limited so, although the device authentication works
as expected, it's far from being user friendly so disable the "qrcode"
UI at all in such case.
Ultimately it should be up to the broker to decide whether to support an
UI or not, but since we can't provide it the service name, we have to
handle it in the module.
At the same time, ignore the local broker when using polkit service.
---
That said this avoids polkit to show the device authentication as it's something we already mentioned we don't want, but we can't by design do this kind of filtering in the PAM module, that should be thinnest layer between authd and the broker, but instead I think we should re-consider refactoring this so that:
1. The broker mandates the supported authentication modes depending on the PAM …
> pam/native: Do not support device authentication mode in polkit

- CONTRIBUTING.md
- docs/explanation/index.md
- docs/howto/configure-authd.md
- docs/howto/index.md
- docs/howto/install-authd.md
- docs/index.md
- docs/reference/cloud-providers.md
- docs/reference/index.md
- docs/reference/troubleshooting.md
This implements the discussed plans for better surfacing broker-specific content in the documentation.
The most notable change is the **introduction of tab-based content for different brokers**. This style of presentation is used immediately on the homepage. The motivation for that change is that the homepage tends to be the most popular page and the first encounter a user has with the documentation; it is therefore a good opportunity to show that there are multiple brokers to choose from, along with supporting documentation. The user can choose the provider/broker that most interests them and they will be pointed directly to broker-specific content. This is made possible by using URL query parameters, which allow toggling of tabs on page visit. When a user chooses `broker x` from a set …
> docs: Surface brokers in docs

- .golangci.yaml
- pam/internal/pam_test/module-transaction-dummy.go
The nolintlint settings must be part of the "linters-settings" list.
Fixes that golangci-lint fails in the CI with:
Failed to run: Error: Command failed: /home/runner/golangci-lint-1.63.4-linux-amd64/golangci-lint config verify
jsonschema: "" does not validate with "/additionalProperties": additional properties 'nolintlint' not allowed
Failed executing command with error: the configuration contains invalid elements
> Fix invalid golangci-lint config

- docs/howto/configure-authd.md
Commit 7872c99a2797b0333cb228ef2316e3c69abfdd1c replaced
https://login.microsoftonline.com/<ISSUER_ID>/v2.0
with
<ISSUER_URL>
However, `ISSUER_URL` is not explained in the documentation or Microsoft Entra admin center, so the user has no indication that the URL should be of the form `https://login.microsoftonline.com/<ISSUER_ID>/v2.0` (where `<ISSUER_ID>` is the Directory (tenant) ID as mentioned earlier on the same page).
Closes #800 
UDENG-6141
> Revert usage of unexplained <ISSUER_URL> placeholder

- pam/internal/gdm/conversation.go
- pam/internal/gdm/extension.go
Fix the definition as it wouldn't work in newer go:
```
./extension.go:91:12: cannot define new methods on non-local type jsonProtoMessage
./extension.go:106:12: cannot define new methods on non-local type jsonProtoMessage
./extension.go:115:12: cannot define new methods on non-local type jsonProtoMessage
./extension.go:119:12: cannot define new methods on non-local type jsonProtoMessage
./extension.go:123:12: cannot define new methods on non-local type jsonProtoMessage
./extension.go:137:12: cannot define new methods on non-local type jsonProtoMessage
FAIL	github.com/ubuntu/authd/pam/internal/gdm [build failed]
```
See: https://github.com/golang/go/issues/71917
UDENG-6160
> pam/gdm: Redefine jsonProtoMessage type for go 1.24

- pam/internal/gdm/conversation.go
- pam/internal/gdm/conversation_test.go
- pam/internal/gdm/main_test.go
I noticed an error locally (not really happening in production since I was injecting some bad code from gdm side):
```
feb 24 16:38:41 ubuntu-vmware gdm-session-worker[96114]: panic: runtime error: invalid memory address or nil pointer dereference
feb 24 16:38:41 ubuntu-vmware gdm-session-worker[96114]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x790190c74b9b]
feb 24 16:38:41 ubuntu-vmware gdm-session-worker[96114]: goroutine 17 [running, locked to thread]:
feb 24 16:38:41 ubuntu-vmware gdm-session-worker[96114]: github.com/ubuntu/authd/pam/internal/gdm.SendData({0x790190f28e20?, 0xc000202000?}, 0x0?)
feb 24 16:38:41 ubuntu-vmware gdm-session-worker[96114]:         /home/marco/Dev/authd/pam/internal/gdm/conversation.go:73 +0x5b
feb 24 16:38:41 ubuntu-vmware …
```
> pam/gdm/conversation: Early handle errors on NewDataFromJSON (fixing potential null pointer)

- .github/workflows/automatic-doc-checks.yml
- .github/workflows/build-deb.yaml
- .github/workflows/qa.yaml
There's no need to perform docs CI jobs if nothing changed, so let's save some CI resources.
> ci/doc-checks: Only perform docs checks on docs changes

- pam/integration-tests/testdata/tapes/native/switch_auth_mode.tape
- pam/internal/adapter/authentication.go
- pam/internal/adapter/focustracker.go
- pam/internal/adapter/model.go
- pam/internal/adapter/nativemodel.go
Fixed handling of focus for authentication stage when not using the CLI interface, and fix the race we had for some time, making impossible to go back to auth-selection if going back from the challenge stage was fast enough (VHS quick typing speed was a good friend here :)).
From main commit:
```
In some cases (when the "goBack{}" request via the 'r' cancel key is
performed very quickly on the UI) we might end up doing a
nativeAuthSelection{} request when we are still technically performing
the stage change from the challenge stage to auth-mode selection.
This was particularly a problem in the "Wait" cases, given that these
events could have been arriving without a proper order, because the
cancellation of the previous event could lead to a delayed stage-change
request that we didn't …
```
> pam/nativemodel: Ensure we're in the expected stage before initiating it

- pam/go-exec/module.c
- pam/integration-tests/cmd/exec-client/modulewrapper.go
- pam/integration-tests/exec_test.go
- pam/internal/dbusmodule/transaction.go
Some random cleanups on the exec module, see commits for datails
UDENG-6256
> pam/go/exec: Code cleanup

- .github/workflows/auto-updates.yaml
- .github/workflows/automatic-doc-checks.yml
- .github/workflows/qa.yaml
This is to follow the specs:
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths
> ci: Use quoted values for paths[-ignore] values

- docs/reference/cloud-providers.md
- Fix the order of cloud providers to be aligned with the table without changing the formatting in the table.
- Fixes https://github.com/ubuntu/authd/issues/843
> doc(ref/cloud-providers): fix swapped order of cloud providers

- docs/conf.py
`github_folder` was deprecated in a recent update to the starter pack and is now replaced with the more generic `repo_folder`.
The change caused failed builds on Read the Docs, which should be fixed by this PR.
> docs: change github_folder to repo_folder

- cmd/authd/integrationtests.go
- internal/services/withexamples.go
- internal/testsdetection/integrationtests.go
- internal/testsdetection/testdata/binary.go
- pam/generate.go
- pam/generate_debug.go
- pam/go-exec/module.c
- pam/integration-tests/cmd/exec-client/client.go
- pam/integration-tests/cmd/exec-client/modulewrapper.go
- pam/integration-tests/sshd_preloader/sshd_preloader.c
- pam/internal/gdm/debug.go
- pam/internal/gdm/extension.h
- pam/internal/gdm/extensions/gdm-custom-json-pam-extension.h
- pam/internal/gdm/extensions/gdm-pam-extensions-common.h
- pam/internal/proto/generate.go
- pam/tools/pam-runner/pam-runner.go
- tools/tools.go
We have a lot of helper files to help us test our project and those are protected to not be built with "go build" to avoid having those in the release binary. To avoid having to update tics configuration every time we rename those files or add new ones, let's tag them and filter those out in the analysis.
> Add tags to ignore static check on helper files

- internal/users/db/db.go
- internal/users/db/db_test.go
- internal/users/db/export_test.go
I noticed that if the schema creation fails (e.g. because the schema is invalid), the database file is still created and authd uses it the next time it's started. That results in authd starting up successfully but in failure of each request which uses the broken database.
Let's avoid that by ensuring that the database file is removed when the schema creation fails.
UDENG-6482
> Remove database on schema creation failure

- internal/users/db/db.go
Let's try applying those suggestions and see if the error still occurs.
Closes #845
UDENG-6472
> Apply suggestions from SQLite FAQ to avoid the "database is locked" error

- .github/workflows/build-deb.yaml
In order to be able to build authd from launchpad recipes we need to use a synchronized repository that contains the sources in a ready-to-build form, however our sources requires vendording the dependencies and cargo filtering and this does not work in builders without an internet connection (and without very recent cargo either).
The good thing is that we're already building the sources ourselves, so we can provide launchpad just them.
While dput'ing the built sources would be an option, it would also requires having an uploader bot with its GPG key, and that's somewhat unsafer, so let's instead just put the sources in a branch that is updated at every push to main and that launchpad can fetch for creating the packages.
This will be handled by …
> ci/build-deb: Push the debian sources to packaging branches

- .github/workflows/qa.yaml
- examplebroker/broker.go
- internal/testutils/args.go
- internal/testutils/daemon.go
- pam/integration-tests/helpers_test.go
- pam/integration-tests/vhs-helpers_test.go
- pam/internal/adapter/authentication.go
- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/commands.go
- pam/internal/adapter/focustracker.go
- pam/internal/adapter/gdmmodel.go
- pam/internal/adapter/gdmmodel_test.go
- pam/internal/adapter/gdmmodel_uimodel_test.go
- pam/internal/adapter/model.go
- pam/internal/adapter/nativemodel.go
- pam/internal/adapter/newpasswordmodel.go
- pam/internal/adapter/qrcodemodel.go
- pam/internal/adapter/reselectbuttonmodel.go
- pam/internal/adapter/textinputmodel.go
- pam/internal/adapter/userselection.go
- pam/internal/pam_test/pam-client-dummy.go
- pam/pam.go
See commits for details, but basically lots of cleanups to ensure that the races are properly monitored and that the artifacts saved in CI, then I decided to tackle the root cause of https://github.com/charmbracelet/bubbletea/issues/909 that was mostly due to the fact that we were, in various cases, updating the models with pointer receivers, instead of relying on the returned and modified value.
Coming with various cleanups.
UDENG-6474
> pam: Fix races handling in VHS tests and fix bubbletea models implementations

- pam/integration-tests/gdm_test.go
We were expecting too many auth mode selections during start authentication in some tests.
Now ensures that we're cleaning the expected values too.
See:
https://github.com/ubuntu/authd/actions/runs/14090553539/job/39465932286
> pam/integration-tests/gdm: Do not expect too many authModes selections

- debian/gbp.conf
Ensure that gbp buildpackage works by using the locally-installed cargo-vendor-filterer, if any.
So trigger the package cleanup before the build with the proper PATH value, to ensure that we can have a properly working gbp buildpackage in all the versions we support.
As per this, building a _clean_ source package is as easy as doing (or binaries can be built in a similar way):
gbp buildpackage -S
> debian/gbp.conf: Use cargo-vendor-filterer from path during build

- .github/workflows/qa.yaml
In order to submit our coverage to TiCS, we need them parsed in Cobertura format. Since we need to parse this for TiCS, let's reuse the assets and upload those Cobertura reports to Codecov as well.
UDENG-5893
> Parse coverage to Cobertura format and upload artifact

- nss/src/passwd/mod.rs
https://github.com/ubuntu/authd/pull/864 introduced some Rust formatting which does not adhere to the rustfmt style.
That was not caught by the "Rust: Code sanity" job, which should be fixed by  https://github.com/canonical/desktop-engineering/pull/67.
> Run `cargo fmt`

- go.mod
govulncheck reports the following vulnerability in go1.23.6
```
Vulnerability #1: GO-2025-3563
Request smuggling due to acceptance of invalid chunked data in net/http
More info: https://pkg.go.dev/vuln/GO-2025-3563
Found in: net/http/internal@go1.23.6
Fixed in: net/http/internal@go1.23.8
```
> Bump Go toolchain version to 1.23.8

- pam/integration-tests/ssh_test.go
- pam/integration-tests/testdata/tapes/cli/form_with_button.tape
- pam/integration-tests/testdata/tapes/cli/mfa_reset_pwquality_auth.tape
- pam/integration-tests/testdata/tapes/cli/optional_password_reset_skip.tape
- pam/integration-tests/testdata/tapes/cli/remember_broker_and_mode.tape
- pam/integration-tests/testdata/tapes/ssh/simple_auth_with_shell.tape
- pam/integration-tests/vhs-helpers_test.go
- pam/internal/adapter/gdmmodel_test.go
As per #882 SSH tests take way more to return back to the terminal, and this leads to random failures in CI.
So give these tests more time to wait for being completed, sadly.
It's also weird that a minor upgrade has such performances implications, but not something we can easily track.
> pam/tests: Fix failures due to timing issues as per recent go updates

- internal/users/db/db_test.go
- internal/users/db/testdata/golden/TestUpdateUserEntry/Update_user_by_changing_attributes
- internal/users/db/testdata/golden/TestUpdateUserEntry/Update_user_does_not_change_shell_if_it_exists
- internal/users/db/update.go
The user's shell should be configurable locally and not overwritten when the user info is being refreshed.
Closes #880 
UDENG-6659
> Don't overwrite shell when updating user entry

- .github/workflows/qa.yaml
Avoid running all the tests if one is failing, since we'd likely need to trigger another test job.
Thus avoid wasting resources
> ci/qa: Use failfast argument flag for tests

- pam/internal/adapter/authentication.go
- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/brokerselection.go
- pam/internal/adapter/debug.go
- pam/internal/adapter/export_test.go
- pam/internal/adapter/gdmmodel_uimodel_test.go
- pam/internal/adapter/list.go
- pam/internal/adapter/model.go
- pam/internal/adapter/nativemodel.go
- pam/internal/adapter/reselectbuttonmodel.go
- pam/internal/adapter/userselection.go
- pam/internal/adapter/utils.go
- pam/internal/adapter/utils_test.go
When debug mode is enabled, during ssh sessions we are disclosing some new-password information.
So avoid this to happen, but also take the occasion to make the messages logging safer and more helpful in debug and test builds so that we can show all the information when it's safe, while not expose anything relevant in release builds.
UDENG-6647
> pam: Use safer handler for debugging bubble tea messages without disclosing information

- pam/internal/adapter/authmodeselection.go
- pam/internal/adapter/list.go
- pam/internal/adapter/nativemodel.go
If the list gets focused we were doing the authentication mode selection
but we didn't properly mark the list as focused (as per not properly
overriding the listFocused message), thus breaking the focus model,
since at global level the user selection was instead considered
focused.
This can break the auto-selection (as seen in some GDM tests), because
on further focus requests the autoSelectedAuthModeID value was set set
again (even if unnecessary) causing further focus calls to lazily using
it.
This should help fixing the gdm [tests failure](https://github.com/ubuntu/authd/actions/runs/14884282528/attempts/1) we got recently due to too-early authentication mode selection.
I still have further improvements ready for that, but let's go simpler first.
> authmodeselection: Actually mark list as focused on focus request

- pam/integration-tests/native_test.go
- pam/integration-tests/testdata/golden/TestNativeAuthenticate/Authenticate_user_successfully_with_password_only_supported_method_in_polkit
- pam/integration-tests/testdata/golden/TestNativeChangeAuthTok/Change_password_successfully_and_authenticate_with_new_one_with_single_broker_and_password_only_supported_method
- pam/integration-tests/testdata/tapes/native/passwd_simple_one_broker_only.tape
- pam/internal/adapter/nativemodel.go
During the challenge phase a "go back" message may have been shown even
if we had no multiple authentication methods or brokers available.
So fix this by actually checking if we can go back
Depends on #914 (as noticed when tuning tests there :))
> pam/nativemodel: Do not show "go back" info message if not supported

- .github/workflows/build-deb.yaml
The "devel" version targets questing since plucky was released.
UDENG-7063
> ci/build-deb: Build debian package targeting plucky

- .github/workflows/build-deb.yaml
Pushing a tag to a feature branch should not result in Debian package being automatically published to the edge PPA.
> Do not release Debian packages for tags on non-main branches

- docs/howto/login-gdm.md
- docs/howto/login-ssh.md
- docs/howto/use-with-nfs.md
- docs/howto/use-with-samba.md
- docs/reference/troubleshooting.md
* Use ini style code blocks for systemd unit files
The plain code blocks had some strange highlighting, like highlighting
the "bin" in `ExecStart=/usr/bin/snap run authd-google -vv`.
* Use single backticks for inline code
Markdown uses single backticks for inline code and three backticks for
code blocks.
* Add code block styles to some blocks
> docs: Improve code block styles

- .github/ISSUE_TEMPLATE/bug_report.yml
When debugging errors caused by updating authd, the system logs become more useful if you know the start and end date of when authd was updated.
> GitHub issue template: Include authd apt history

- internal/users/localentries/localgroups.go
* Print log message with log level "notice"
The default log level for authd is "notice", so messages with log level
"info" are not displayed by default. That caused me some confusion when
I added the user to a new "linux-" group in Entra, which the user wasn't
added to during login and nothing showed up about it in the logs.
The reason was that the group name contained a typo, so gpasswd couldn't
find a local group of the same name. We should print a log message
that's shown in the default log level when that happens.
* Make it clearer why we're ignoring the error.
> Improve log message

- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/daemon_test.go
- cmd/authd/daemon/export_test.go
- internal/users/manager.go
In case the users config was not set we ended up with an invalid one, since by default we were initializing a zeroed pam.UsersConfig value instead of the default one.
This is likely not an issue in reality, but be consistent with what we do for other configuration parameters and add tests to ensure that the user parameters behave as expected
> authd/daemon: Fix parsing users config if was not defined

- debian/authd.socket
If the accounts service is started first, it doesn't find any authd users.
Closes #965
> Start authd.socket before accounts-daemon.service

- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/daemon_test.go
The `PersistentPreRunE` method did things which should not be done for subcommands like `version`. We don't need to parse the config file to print the authd version, and we definitely don't need to migrate the database.
Also add a `--check-config` flag which can be used in tests which check config parsing instead of the `version` command.
> Fix `version` command trying to migrate

- cmd/authd/daemon/daemon.go
- cmd/authd/daemon/daemon_test.go
authd is not a CLI tool, so there is no need to generate shell completion scripts.
> Remove the completion subcommand

- docs/.custom_wordlist.txt
- docs/.sphinx/spellingcheck.yaml
- docs/howto/configure-authd.md
- docs/howto/index.md
- docs/howto/use-with-lxd.md
- docs/reference/troubleshooting.md
A user reported issues authenticating with authd from LXD containers: https://github.com/ubuntu/authd/issues/819
This PR is based on the solutions offered in response. It adds:
* A brief and self-contained how-to guide **Use authd with LXD** on configuring UID/GID ranges for LXD. _I considered adding this to the general installation and configuration guide, but it seemed too specific and could distract users interested in more conventional use-cases._
* A brief section on the LXD issue in the **Troubleshooting** reference that points to the new guide. _This helps increase the probability that people looking for the solution will find it._
* A reference to the file for configuring the authd service to the **Configure authd** guide. _There might be other contexts in which users want to …
> docs: add information on configuring ID ranges for LXD

- internal/errno/errno_c.go
- internal/users/locking/locking_bwrap_test.go
- internal/users/locking/locking_c.go
We've seen the test fail in the CI with:
Error Trace: /home/runner/work/authd/authd/internal/users/locking/locking_bwrap_test.go:266
Error:       Target error should be in err chain:
expected: "failed to lock the shadow password database: timeout"
in chain: "failed to lock the shadow password database: Interrupted system call"
Test:        TestLockingLockedDatabaseFailsAfterTimeout
The reason is probably that the alarm set by lckpwdf does sometimes work in the CI, so lckpwdf returns an error before our own 16 second timeout is reached, resulting in a different error to be returned.
Return a ErrLockTimeout when that happens.
> locking: Return ErrLockTimeout on EINTR

- log/handler.go
- log/log.go
SetOutput used the slog.TextHandler instead of the default slog.defaultHandler.
That produced output like this:
time=2025-06-23T16:48:23.615+02:00 level=DEBUG msg="Sending to GDM: {\"type\":\"request\",\"request\":{\"type\":\"uiLayoutCapabilities\",\"uiLayoutCapabilities\":{}}}"
This commit uses a custom handler which produces output similar to the slog.defaultHandler (which we can't use because it's not exported), except that it omits the date and only prints the time instead (because we're generally not interested in the date when looking at test logs).
It produces output like this:
16:48:09 DEBUG Sending to GDM: {"type":"request","request":{"type":"uiLayoutCapabilities","uiLayoutCapabilities":{}}}
> More readable logs of pam integration tests

- internal/services/permissions/testutils.go
It's more efficient to use `os.Getuid` (or `os.Geteuid`) than `user.Current()`, because the latter uses `getpwuid` which sends an NSS request while the former just retrieves the UID of the current process from the kernel via the `getuid` (or `geteuid`) syscall.
We want `geteuid` instead of `getuid` because this is used for permission checking (in tests, but still).
> testutils: Get current effective UID via os.Geteuid

- internal/testutils/bubblewrap.go
- internal/users/locking/locking_bwrap_test.go
The test case failed on my system which has authd installed, because the `getent group` command also returned the authd groups.
Fix that by specifying which group entries `getent` should return.
> Fix TestUsersLockingInBubbleWrap/TestReadWhileLocked

- docs/.custom_wordlist.txt
- docs/howto/configure-authd.md
Adds section to configuration guide on modifying the local password policy for authd, with a small example of setting the minimum password length.
Change was prompted by https://github.com/ubuntu/authd/issues/958, which outlined issues with InTune's password compliance checking.
UDENG-7210
> docs: section on configuring password quality

- nss/integration-tests/integration_test.go
The test was using the authd instance running on my system, causing the tests which expect authd to not be running to fail.
> Fix NSS integration tests

- examplebroker/broker.go
- internal/services/user/user.go
We used to silently ignore errors returned by the call to the broker's UserPreCheck method.
We now differentiate between "user not permitted to log in via SSH for the first time", which we log with debug level, and unexpected errors, which we log with error level.
> Log UserPreCheck errors

- internal/users/localentries/getgrent_c.go
- internal/users/localentries/getgrent_test.go
- internal/users/localentries/getpwent_c.go
- internal/users/localentries/getpwent_test.go
These functions were never used. On https://github.com/ubuntu/authd/pull/993 we had a use case for them, but then decided to use `user.Lookup`/`user.LookupGroup` instead, so let's remove them.
> localentries: Remove unused functions

- CONTRIBUTING.md
- docs/.custom_wordlist.txt
- docs/conf.py
The contributing guidelines should include guidance relating to docs contributions (ways to contribute, building, testing).
The Open Documentation Academy should also be referenced, as authd is now a participating project, and new contributors to open source may want to get involved through that channel.
Other changes: fixed a link and a typo.
> [!NOTE]
> The changes are also trancluded to the relevant section of the docs
> See [relevant section in the preview](https://canonical-ubuntu-documentation-library--1015.com.readthedocs.build/authd/1015/howto/contributing/#contributing-to-the-documentation) 
UDENG-7330
> docs: add doc contribution guidelines

- internal/fileutils/fileutils.go
- internal/fileutils/fileutils_test.go
- internal/testutils/args.go
- internal/testutils/rust.go
- nss/build.rs
I couldn't figure out exactly why, but `cargo build` always treated the nss crate as dirty and re-compiled it even when nothing changed in between two runs:
```
cargo build --verbose
[...]
Dirty nss v0.1.0 (/home/user/projects/authd/nss): the file `nss/..` has changed (1756139002.017575102s, 2s after last build at 1756139000.627582074s)
Compiling nss v0.1.0 (/home/user/projects/authd/nss)
```
Using `"../internal/proto"` instead of `"../"` as the includes directory in the `compile_protos` call fixes that.
UDENG-7825
> Fix cargo always treating nss crate as dirty

- .github/workflows/auto-updates.yaml
- .github/workflows/build-deb.yaml
- .github/workflows/qa.yaml
To avoid this warning being printed:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> ci: Use apt-get instead of apt

- README.md
- SECURITY.md
- docs/howto/changing-versions.md
- docs/index.md
The `latest` version of docs for authd are now named `edge`, to better align with the available versions of the software.
This change was managed through the ReadTheDocs interface and is now live.
In addition, for some time, the URL for our docs has been documentation.ubuntu.com/authd and not canonical-authd.readthedocs.hosted.
This PR:
* Replace readthedocs.hosted URLs with documentation.ubuntu
* Updates references to "latest" docs to "edge" docs
UDENG-8051
> docs: update stable and edge URLs

- internal/brokers/manager.go
- internal/services/pam/pam.go
It took me a quite long time to make sense of that comment. Let's rephrase it and move it to the place where we have the necessary context (the broker ID being fetched from the database) to make sense of it.
> Improve comment of BrokerExists() function

- docs/explanation/index.md
- docs/howto/index.md
- docs/reference/index.md
A user does not necessarily understand Diataxis (how-to, reference, explanation) and the landing page should give context for the top-level grouping of pages and the individual sub-sets listed.
* Adds top-level context statement between two headers where it is absent
* Makes statements before links more consistent and descriptive
* Avoids telling users to "find" or "read", and just gives them the relevant information to provide context for the link(s) that follow. It's obvious that the documentation is for reading the information is for finding
* Adds missing header for architecture in reference index
* Provides better link text if it is unclear
Note: the documentation team are expected to engage in a larger review of landing pages specifically next cycle, where further improvements are …
> docs: improve context statements on landing pages

- debian/control
Some of our dependencies (deranged v0.5.4) require a newer rustc version (1.81) than the one installed by default on Noble (1.75). Fortunately, the Noble archives also include newer cargo versions, up to 1.82, so let's install that.
UDENG-8123
> debian/control: Add build dependency on cargo 1.82

- docs/.custom_wordlist.txt
- docs/conf.py
- docs/explanation/index.md
- docs/explanation/security.md
- docs/howto/configure-authd.md
- docs/howto/login-ssh.md
First draft of a security overview for authd. See the [Jira ticket](https://warthogs.atlassian.net/browse/UDENG-7652) for context.
UDENG-7652
> Add security overview doc

- .github/workflows/build-deb.yaml
- .github/workflows/cla-check.yaml
- .github/workflows/git.yml
- .github/workflows/qa.yaml
- .github/workflows/validate-dependabot.yaml
Our CI jobs run for a long time and use a lot of resources.
It happens quite often to me that, after I push something to a PR, I find something to small to fix (e.g. improve the commit message) and push that fix soon after. We can save some resources by automatically cancelling in-progress workflows on new pushes to the same branch (I do that manually sometimes, but that's wasting my time).
The implementation is directly from the example of the concurrency keyword: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-using-concurrency-and-the-default-behavior
UDENG-8268
> ci: Automatically cancel in-progress workflow runs on push
